-- ============================================
-- Learn Swedish: Vocab Power Pack
-- 300+ Additional Words (A1-B2)
-- ============================================

INSERT INTO vocabulary (swedish, english, example_sv, example_en, category, level) VALUES
  -- Travel & Directions
  ('resa', 'to travel / trip', 'Jag älskar att resa till nya länder.', 'I love to travel to new countries.', 'travel', 'A1'),
  ('väska', 'bag / suitcase', 'Min väska är tung.', 'My bag is heavy.', 'travel', 'A1'),
  ('pass', 'passport', 'Glöm inte ditt pass!', 'Don''t forget your passport!', 'travel', 'A1'),
  ('biljett', 'ticket', 'Här är din biljett.', 'Here is your ticket.', 'travel', 'A1'),
  ('tåg', 'train', 'Tåget går klockan nio.', 'The train leaves at nine o''clock.', 'travel', 'A1'),
  ('flygplan', 'airplane', 'Flygplanet landar om en timme.', 'The airplane lands in an hour.', 'travel', 'A2'),
  ('hotell', 'hotel', 'Vi bor på ett fint hotell.', 'We are staying at a nice hotel.', 'travel', 'A1'),
  ('karta', 'map', 'Kan du visa mig på kartan?', 'Can you show me on the map?', 'travel', 'A1'),
  ('höger', 'right', 'Sväng till höger vid nästa korsning.', 'Turn right at the next intersection.', 'directions', 'A1'),
  ('vänster', 'left', 'Gå till vänster efter bron.', 'Go left after the bridge.', 'directions', 'A1'),
  ('rakt fram', 'straight ahead', 'Fortsätt rakt fram.', 'Continue straight ahead.', 'directions', 'A1'),
  ('plats', 'place / seat', 'Är den här platsen ledig?', 'Is this seat free?', 'travel', 'A1'),
  ('äventyr', 'adventure', 'Vi är redo för ett äventyr.', 'We are ready for an adventure.', 'travel', 'B1'),
  ('destination', 'destination', 'Vi har nått vår destination.', 'We have reached our destination.', 'travel', 'B1'),
  ('sevärdhet', 'sight / attraction', 'Stockholm har många sevärdheter.', 'Stockholm has many sights.', 'travel', 'B2'),

  -- Career & Work
  ('jobb', 'job / work', 'Jag letar efter ett nytt jobb.', 'I am looking for a new job.', 'career', 'A1'),
  ('kollega', 'colleague', 'Mina kollegor är mycket trevliga.', 'My colleagues are very nice.', 'career', 'A2'),
  ('kontor', 'office', 'Vårt kontor ligger i centrum.', 'Our office is located in the center.', 'career', 'A1'),
  ('möte', 'meeting', 'Jag har ett viktigt möte kl 10.', 'I have an important meeting at 10.', 'career', 'A2'),
  ('anställd', 'employee', 'Företaget har hundra anställda.', 'The company has one hundred employees.', 'career', 'B1'),
  ('lön', 'salary', 'När får vi lön?', 'When do we get paid?', 'career', 'A2'),
  ('ansökan', 'application', 'Jag skickade min ansökan igår.', 'I sent my application yesterday.', 'career', 'B1'),
  ('intervju', 'interview', 'Intervjun gick jättebra.', 'The interview went really well.', 'career', 'B1'),
  ('projekt', 'project', 'Vi arbetar på ett spännande projekt.', 'We are working on an exciting project.', 'career', 'B1'),
  ('ansvar', 'responsibility', 'Han har mycket ansvar på jobbet.', 'He has a lot of responsibility at work.', 'career', 'B2'),
  ('erfarenhet', 'experience', 'Jag har lång erfarenhet av IT.', 'I have long experience in IT.', 'career', 'B2'),
  ('utbildning', 'education', 'Utbildningen var mycket lärorik.', 'The education was very instructive.', 'career', 'B2'),
  ('kompetens', 'competence / skill', 'Vi värdesätter din kompetens.', 'We value your competence.', 'career', 'B2'),
  ('karriär', 'career', 'Hon vill göra karriär inom medicin.', 'She wants to make a career in medicine.', 'career', 'B1'),
  ('chef', 'boss / manager', 'Min chef är rättvis.', 'My boss is fair.', 'career', 'A2'),

  -- Emotions & Feelings
  ('glad', 'happy', 'Jag blir glad av att se dig.', 'I get happy seeing you.', 'emotions', 'A1'),
  ('ledsen', 'sad', 'Varför är du ledsen?', 'Why are you sad?', 'emotions', 'A1'),
  ('arg', 'angry', 'Bli inte arg på mig.', 'Don''t get angry with me.', 'emotions', 'A1'),
  ('rädd', 'scared / afraid', 'Är du rädd för mörkret?', 'Are you afraid of the dark?', 'emotions', 'A1'),
  ('trött', 'tired', 'Jag är så trött efter jobbet.', 'I am so tired after work.', 'emotions', 'A1'),
  ('pigg', 'alert / awake', 'Jag känner mig pigg idag.', 'I feel alert today.', 'emotions', 'A2'),
  ('förvirrad', 'confused', 'Jag är lite förvirrad av reglerna.', 'I am a bit confused by the rules.', 'emotions', 'B1'),
  ('förväntansfull', 'expectant / excited', 'Barnen är förväntansfulla inför julen.', 'The children are excited for Christmas.', 'emotions', 'B2'),
  ('besviken', 'disappointed', 'Jag blev besviken på resultatet.', 'I was disappointed with the result.', 'emotions', 'B1'),
  ('överraskad', 'surprised', 'Jag blev verkligen överraskad.', 'I was really surprised.', 'emotions', 'A2'),
  ('lugn', 'calm', 'Naturen gör mig lugn.', 'Nature makes me calm.', 'emotions', 'A2'),
  ('orolig', 'worried', 'Mamma är orolig för dig.', 'Mom is worried about you.', 'emotions', 'A2'),
  ('lycklig', 'fortunate / happy', 'De lever ett lyckligt liv.', 'They live a happy life.', 'emotions', 'B1'),
  ('ensam', 'lonely / alone', 'Ibland känns det ensamt.', 'Sometimes it feels lonely.', 'emotions', 'A2'),
  ('nyfiken', 'curious', 'Jag är nyfiken på vad som händer.', 'I am curious about what is happening.', 'emotions', 'A2'),

  -- Nature & Environment
  ('skog', 'forest', 'Sverige har mycket skog.', 'Sweden has a lot of forest.', 'nature', 'A1'),
  ('sjö', 'lake', 'Sjön är spegelblank ikväll.', 'The lake is perfectly still tonight.', 'nature', 'A1'),
  ('berg', 'mountain', 'Berget är täckt av snö.', 'The mountain is covered in snow.', 'nature', 'A2'),
  ('träd', 'tree', 'Äppelträdet blommar nu.', 'The apple tree is blooming now.', 'nature', 'A1'),
  ('blomma', 'flower', 'Vilken vacker blomma!', 'What a beautiful flower!', 'nature', 'A1'),
  ('himmel', 'sky', 'Himlen är blå idag.', 'The sky is blue today.', 'nature', 'A1'),
  ('moln', 'cloud', 'Det är inga moln på himlen.', 'There are no clouds in the sky.', 'nature', 'A1'),
  ('regn', 'rain', 'Jag gillar doften av regn.', 'I like the smell of rain.', 'nature', 'A1'),
  ('snö', 'snow', 'Vi hoppas på snö till jul.', 'We hope for snow for Christmas.', 'nature', 'A1'),
  ('vind', 'wind', 'Vinden blåser kallt.', 'The wind is blowing cold.', 'nature', 'A1'),
  ('miljö', 'environment', 'Vi måste tänka på miljön.', 'We must think about the environment.', 'nature', 'B1'),
  ('klimat', 'climat', 'Klimatet förändras snabbt.', 'The climate is changing fast.', 'nature', 'B2'),
  ('skärgård', 'archipelago', 'Stockholms skärgård är vacker.', 'Stockholm''s archipelago is beautiful.', 'nature', 'B1'),
  ('naturreservat', 'nature reserve', 'Vi vandrar i ett naturreservat.', 'We are hiking in a nature reserve.', 'nature', 'B2'),
  ('hållbarhet', 'sustainability', 'Företaget satsar på hållbarhet.', 'The company invests in sustainability.', 'nature', 'B2'),

  -- Technology & Media
  ('dator', 'computer', 'Min dator är gammal.', 'My computer is old.', 'technology', 'A1'),
  ('telefon', 'telephone', 'Var är min telefon?', 'Where is my phone?', 'technology', 'A1'),
  ('internet', 'internet', 'Internet är segt idag.', 'The internet is slow today.', 'technology', 'A1'),
  ('hemsida', 'website', 'Kolla på vår hemsida.', 'Check out our website.', 'technology', 'A2'),
  ('applikation', 'application / app', 'Ladda ner vår nya app.', 'Download our new app.', 'technology', 'B1'),
  ('programvara', 'software', 'Vi behöver uppdatera vår programvara.', 'We need to update our software.', 'technology', 'B2'),
  ('skärm', 'screen', 'Skärmen är trasig.', 'The screen is broken.', 'technology', 'A2'),
  ('lösenord', 'password', 'Kom ihåg ditt lösenord.', 'Remember your password.', 'technology', 'A2'),
  ('sociala medier', 'social media', 'Jag använder inte sociala medier.', 'I don''t use social media.', 'media', 'A2'),
  ('nyheter', 'news', 'Jag läser nyheterna varje dag.', 'I read the news every day.', 'media', 'A2'),
  ('information', 'information', 'Här är mer information.', 'Here is more information.', 'technology', 'A2'),
  ('utveckling', 'development', 'Teknikens utveckling går snabbt.', 'Technological development is moving fast.', 'technology', 'B2'),
  ('artificiell intelligens', 'artificial intelligence', 'AI kommer förändra världen.', 'AI will change the world.', 'technology', 'B2'),
  ('säkerhet', 'security / safety', 'Säkerhet är vår prioritet.', 'Security is our priority.', 'technology', 'B1'),
  ('databas', 'database', 'Vi sparar allt i en databas.', 'We save everything in a database.', 'technology', 'B2'),

  -- Home & Daily Life
  ('hem', 'home', 'Jag längtar hem.', 'I long for home.', 'daily life', 'A1'),
  ('lägenhet', 'apartment', 'Vi bor i en liten lägenhet.', 'We live in a small apartment.', 'home', 'A1'),
  ('kök', 'kitchen', 'Köket är husets hjärta.', 'The kitchen is the heart of the house.', 'home', 'A1'),
  ('vardagsrum', 'living room', 'Vi ser på TV i vardagsrummet.', 'We watch TV in the living room.', 'home', 'A1'),
  ('sovrum', 'bedroom', 'Mitt sovrum är målat blått.', 'My bedroom is painted blue.', 'home', 'A1'),
  ('badrum', 'bathroom', 'Badrummet är nyrenoverat.', 'The bathroom is newly renovated.', 'home', 'A1'),
  ('möbler', 'furniture', 'Vi behöver köpa nya möbler.', 'We need to buy new furniture.', 'home', 'A2'),
  ('fönster', 'window', 'Titta ut genom fönstret.', 'Look out through the window.', 'home', 'A1'),
  ('dörr', 'door', 'Stäng dörren, tack.', 'Close the door, please.', 'home', 'A1'),
  ('granne', 'neighbor', 'Våra grannar är snälla.', 'Our neighbors are kind.', 'daily life', 'A2'),
  ('hyra', 'rent', 'Hyran är ganska hög.', 'The rent is quite high.', 'home', 'A2'),
  ('städa', 'to clean', 'Jag måste städa idag.', 'I must clean today.', 'daily life', 'A2'),
  ('tvätta', 'to wash / do laundry', 'Ska du tvätta imorgon?', 'Are you doing laundry tomorrow?', 'daily life', 'A2'),
  ('handla', 'to shop / buy groceries', 'Vi ska gå och handla.', 'We are going grocery shopping.', 'daily life', 'A1'),
  ('frukost', 'breakfast', 'Vad åt du till frukost?', 'What did you eat for breakfast?', 'daily life', 'A1'),

  -- Abstract & Advanced (B1/B2)
  ('möjlighet', 'opportunity / possibility', 'Det här är en bra möjlighet.', 'This is a good opportunity.', 'abstract', 'B1'),
  ('skillnad', 'difference', 'Vad är skillnaden?', 'What is the difference?', 'abstract', 'B1'),
  ('utmaning', 'challenge', 'Det var en stor utmaning.', 'It was a big challenge.', 'abstract', 'B1'),
  ('lösning', 'solution', 'Vi hittade en bra lösning.', 'We found a good solution.', 'abstract', 'B1'),
  ('samhälle', 'society', 'Vi lever i ett demokratiskt samhälle.', 'We live in a democratic society.', 'abstract', 'B2'),
  ('rättvisa', 'justice', 'Rättvisa är viktigt.', 'Justice is important.', 'abstract', 'B2'),
  ('frihet', 'freedom', 'Yttrandefrihet är en mänsklig rättighet.', 'Freedom of speech is a human right.', 'abstract', 'B2'),
  ('kunskap', 'knowledge', 'Kunskap är makt.', 'Knowledge is power.', 'abstract', 'B1'),
  ('berättelse', 'story', 'Det var en spännande berättelse.', 'It was an exciting story.', 'abstract', 'B1'),
  ('förändring', 'change', 'Förändring tar tid.', 'Change takes time.', 'abstract', 'B2'),
  ('påverka', 'to influence / affect', 'Det påverkar vårt beslut.', 'It affects our decision.', 'abstract', 'B2'),
  ('beslut', 'decision', 'Vi har tagit ett beslut.', 'We have made a decision.', 'abstract', 'B1'),
  ('erbjuda', 'to offer', 'De erbjuder bra service.', 'They offer good service.', 'abstract', 'B1'),
  ('samarbete', 'cooperation', 'Vi hoppas på ett bra samarbete.', 'We hope for a good cooperation.', 'abstract', 'B2'),
  ('utveckla', 'to develop', 'Vi vill utveckla vår verksamhet.', 'We want to develop our business.', 'abstract', 'B2'),

  -- Adjectives & Descriptors
  ('vacker', 'beautiful', 'Sverige är vackert på sommaren.', 'Sweden is beautiful in the summer.', 'adjectives', 'A1'),
  ('viktig', 'important', 'Det är mycket viktigt.', 'It is very important.', 'adjectives', 'A1'),
  ('svår', 'difficult', 'Svenska är inte så svårt.', 'Swedish is not so difficult.', 'adjectives', 'A1'),
  ('enkel', 'simple / easy', 'Det är en enkel uppgift.', 'It is a simple task.', 'adjectives', 'A1'),
  ('billig', 'cheap', 'Maten är ganska billig här.', 'The food is quite cheap here.', 'adjectives', 'A1'),
  ('dyr', 'expensive', 'Bilen var jättedyr.', 'The car was very expensive.', 'adjectives', 'A1'),
  ('snabb', 'fast', 'Han springer snabbt.', 'He runs fast.', 'adjectives', 'A1'),
  ('långsam', 'slow', 'Bussen är långsam idag.', 'The bus is slow today.', 'adjectives', 'A1'),
  ('ny', 'new', 'Jag har en ny tröja.', 'I have a new sweater.', 'adjectives', 'A1'),
  ('gammal', 'old', 'Staden är mycket gammal.', 'The city is very old.', 'adjectives', 'A1'),
  ('fantastisk', 'fantastic', 'Vilken fantastisk dag!', 'What a fantastic day!', 'adjectives', 'A2'),
  ('förfärlig', 'terrible', 'Det är ett förfärligt väder.', 'It is terrible weather.', 'adjectives', 'B1'),
  ('intressant', 'interesting', 'Boken är mycket intressant.', 'The book is very interesting.', 'adjectives', 'A2'),
  ('tråkig', 'boring / sad', 'Det är en tråkig film.', 'It is a boring movie.', 'adjectives', 'A1'),
  ('mysig', 'cozy', 'Vi har det mysigt hemma.', 'We are having a cozy time at home.', 'adjectives', 'A2'),

  -- Health & Body
  ('kropp', 'body', 'Man måste ta hand om sin kropp.', 'One must take care of one''s body.', 'health', 'A2'),
  ('hälsa', 'health', 'Hälsan är viktigast.', 'Health is most important.', 'health', 'A2'),
  ('huvud', 'head', 'Jag har ont i huvudet.', 'I have a headache.', 'body', 'A1'),
  ('hand', 'hand', 'Tvätta händerna före maten.', 'Wash your hands before eating.', 'body', 'A1'),
  ('fot', 'foot', 'Mina fötter gör ont.', 'My feet hurt.', 'body', 'A1'),
  ('öga', 'eye', 'Hon har blåa ögon.', 'She has blue eyes.', 'body', 'A1'),
  ('öra', 'ear', 'Han har stora öron.', 'He has big ears.', 'body', 'A1'),
  ('mun', 'mouth', 'Öppna munnen.', 'Open your mouth.', 'body', 'A1'),
  ('sjukhus', 'hospital', 'Var ligger närmaste sjukhus?', 'Where is the nearest hospital?', 'health', 'A1'),
  ('läkare', 'doctor', 'Jag måste träffa en läkare.', 'I must see a doctor.', 'health', 'A1'),
  ('medicin', 'medicine', 'Glöm inte att ta din medicin.', 'Don''t forget to take your medicine.', 'health', 'A2'),
  ('recept', 'prescription / recipe', 'Läkaren skrev ett recept.', 'The doctor wrote a prescription.', 'health', 'B1'),
  ('sjuksköterska', 'nurse', 'Sjuksköterskan var mycket hjälpsam.', 'The nurse was very helpful.', 'health', 'B1'),
  ('må bra', 'to feel well', 'Jag mår bra idag.', 'I feel well today.', 'health', 'A1'),
  ('träna', 'to exercise / train', 'Jag gillar att träna på gym.', 'I like to exercise at the gym.', 'health', 'A1'),

  -- Leisure & Hobbies
  ('fritid', 'leisure time', 'Vad gör du på din fritid?', 'What do you do in your leisure time?', 'leisure', 'A2'),
  ('hobby', 'hobby', 'Min hobby är fotografering.', 'My hobby is photography.', 'leisure', 'A2'),
  ('musik', 'music', 'Jag lyssnar på musik hela tiden.', 'I listen to music all the time.', 'leisure', 'A1'),
  ('sport', 'sport', 'Gillar du sport?', 'Do you like sports?', 'leisure', 'A1'),
  ('film', 'movie', 'Ska vi gå på film?', 'Shall we go to a movie?', 'leisure', 'A1'),
  ('läsa', 'to read', 'Jag älskar att läsa böcker.', 'I love to read books.', 'leisure', 'A1'),
  ('skriva', 'to write', 'Hon skriver en dagbok.', 'She writes a diary.', 'leisure', 'A1'),
  ('måla', 'to paint', 'Han målar en tavla.', 'He is painting a picture.', 'leisure', 'A1'),
  ('sjunga', 'to sing', 'Vi sjunger i kör.', 'We sing in a choir.', 'leisure', 'A1'),
  ('dansa', 'to dance', 'Vill du dansa?', 'Do you want to dance?', 'leisure', 'A1'),
  ('promenad', 'walk', 'Vi tar en promenad i parken.', 'We are taking a walk in the park.', 'leisure', 'A1'),
  ('fika', 'coffee break with snack', 'Ska vi fika?', 'Shall we have a fika?', 'leisure', 'A1'),
  ('resa', 'to travel', 'Att resa är att leva.', 'To travel is to live.', 'leisure', 'A1'),
  ('spela', 'to play', 'Jag gillar att spela gitarr.', 'I like to play guitar.', 'leisure', 'A1'),
  ('vän', 'friend', 'Han är min bästa vän.', 'He is my best friend.', 'leisure', 'A1'),

  -- Clothing & Fashion
  ('kläder', 'clothing', 'Jag behöver nya kläder.', 'I need new clothes.', 'fashion', 'A1'),
  ('skor', 'shoes', 'Dina skor är snygga.', 'Your shoes are stylish.', 'fashion', 'A1'),
  ('byxor', 'pants / trousers', 'Dessa byxor är för långa.', 'These pants are too long.', 'fashion', 'A1'),
  ('tröja', 'sweater / shirt', 'Jag har på mig en varm tröja.', 'I am wearing a warm sweater.', 'fashion', 'A1'),
  ('jacka', 'jacket', 'Ta på dig jackan!', 'Put on your jacket!', 'fashion', 'A1'),
  ('mössa', 'beanie / hat', 'Det är kallt, ta på dig en mössa.', 'It''s cold, put on a beanie.', 'fashion', 'A1'),
  ('vantar', 'mittens / gloves', 'Jag har tappat mina vantar.', 'I have lost my mittens.', 'fashion', 'A2'),
  ('halsduk', 'scarf', 'Min halsduk är röd.', 'My scarf is red.', 'fashion', 'A2'),
  ('klänning', 'dress', 'Hon har en vacker klänning.', 'She has a beautiful dress.', 'fashion', 'A2'),
  ('kjol', 'skirt', 'Kjolen är ny.', 'The skirt is new.', 'fashion', 'A2'),
  ('strumpor', 'socks', 'Jag behöver köpa strumpor.', 'I need to buy socks.', 'fashion', 'A1'),
  ('paraply', 'umbrella', 'Glöm inte paraplyet, det regnar.', 'Don''t forget the umbrella, it''s raining.', 'fashion', 'A1'),
  ('väska', 'handbag', 'Hon bär en liten väska.', 'She is carrying a small bag.', 'fashion', 'A1'),
  ('glasögon', 'glasses', 'Jag ser inte utan mina glasögon.', 'I can''t see without my glasses.', 'fashion', 'A2'),
  ('storlek', 'size', 'Vilken storlek har du?', 'What size do you have?', 'fashion', 'A1'),

  -- Education & Learning
  ('skola', 'school', 'Skolan börjar kl 8.', 'School starts at 8.', 'education', 'A1'),
  ('universitet', 'university', 'Hon studerar på universitetet.', 'She is studying at the university.', 'education', 'A2'),
  ('lärare', 'teacher', 'Vår lärare är pedagogisk.', 'Our teacher is pedagogical.', 'education', 'A1'),
  ('elev', 'student (primary/secondary)', 'Eleverna har prov idag.', 'The students have a test today.', 'education', 'A2'),
  ('student', 'student (higher ed)', 'Jag är student i Lund.', 'I am a student in Lund.', 'education', 'A1'),
  ('läxa', 'homework', 'Har du gjort din läxa?', 'Have you done your homework?', 'education', 'A1'),
  ('prov', 'test / exam', 'Provet var ganska svårt.', 'The test was quite difficult.', 'education', 'A2'),
  ('betyg', 'grade / mark', 'Fick du bra betyg?', 'Did you get good grades?', 'education', 'B1'),
  ('ämne', 'subject', 'Vilket är ditt favoritämne?', 'Which is your favorite subject?', 'education', 'A2'),
  ('språk', 'language', 'Hur många språk talar du?', 'How many languages do you speak?', 'education', 'A1'),
  ('ordlista', 'vocabulary list', 'Här är en bra ordlista.', 'Here is a good vocabulary list.', 'education', 'A2'),
  ('lexikon', 'dictionary', 'Slå upp ordet i ett lexikon.', 'Look up the word in a dictionary.', 'education', 'B1'),
  ('grammar', 'grammatik', 'Grammatiken är logisk.', 'The grammar is logical.', 'education', 'B1'),
  ('förstå', 'to understand', 'Jag förstår vad du menar.', 'I understand what you mean.', 'education', 'A1'),
  ('lära sig', 'to learn', 'Det är kul att lära sig nya saker.', 'It is fun to learn new things.', 'education', 'A1'),

  -- Time Expressions
  ('nu', 'now', 'Vi måste gå nu.', 'We must go now.', 'time', 'A1'),
  ('senare', 'later', 'Vi ses senare.', 'See you later.', 'time', 'A1'),
  ('snart', 'soon', 'Maten är färdig snart.', 'The food will be ready soon.', 'time', 'A1'),
  ('alltid', 'always', 'Jag kommer alltid minnas dig.', 'I will always remember you.', 'time', 'A1'),
  ('aldrig', 'never', 'Jag har aldrig varit i Kina.', 'I have never been to China.', 'time', 'A1'),
  ('ofta', 'often', 'Vi fikar ofta tillsammans.', 'We often have fika together.', 'time', 'A1'),
  ('sällan', 'seldom', 'Det händer sällan.', 'It seldom happens.', 'time', 'A2'),
  ('ibland', 'sometimes', 'Ibland regnar det i Göteborg.', 'Sometimes it rains in Gothenburg.', 'time', 'A1'),
  ('idag', 'today', 'Vad ska du göra idag?', 'What are you doing today?', 'time', 'A1'),
  ('igår', 'yesterday', 'Igår var det vackert väder.', 'Yesterday the weather was beautiful.', 'time', 'A1'),
  ('imorgon', 'tomorrow', 'Vi åker hem imorgon.', 'We are going home tomorrow.', 'time', 'A1'),
  ('vecka', 'week', 'Det är sju dagar på en vecka.', 'There are seven days in a week.', 'time', 'A1'),
  ('månad', 'month', 'Vilken månad är det nu?', 'Which month is it now?', 'time', 'A1'),
  ('år', 'year', 'Ett år har 365 dagar.', 'A year has 365 days.', 'time', 'A1'),
  ('tidigare', 'earlier / before', 'Jag har hört det tidigare.', 'I have heard that before.', 'time', 'A2'),

  -- Social & Communication
  ('prata', 'to talk / speak', 'Kan vi prata lite?', 'Can we talk a bit?', 'communication', 'A1'),
  ('diskutera', 'to discuss', 'Vi måste diskutera det här.', 'We must discuss this.', 'communication', 'B1'),
  ('berätta', 'to tell', 'Berätta en historia!', 'Tell a story!', 'communication', 'A2'),
  ('fråga', 'to ask / question', 'Får jag ställa en fråga?', 'May I ask a question?', 'communication', 'A1'),
  ('svara', 'to answer', 'Svara på min fråga, tack.', 'Answer my question, please.', 'communication', 'A1'),
  ('lyssna', 'to listen', 'Lyssna på musiken.', 'Listen to the music.', 'communication', 'A1'),
  ('tyst', 'silent / quiet', 'Var tyst, snälla.', 'Be quiet, please.', 'communication', 'A1'),
  ('högljudd', 'loud', 'Musiken är för högljudd.', 'The music is too loud.', 'communication', 'A2'),
  ('överens', 'in agreement', 'Vi är helt överens.', 'We are completely in agreement.', 'communication', 'B1'),
  ('asikt', 'opinion', 'Vad är din åsikt?', 'What is your opinion?', 'communication', 'B1'),
  ('meddelande', 'message', 'Jag skickade ett meddelande.', 'I sent a message.', 'communication', 'A2'),
  ('samtal', 'conversation / call', 'Tack för ett bra samtal.', 'Thank you for a good conversation.', 'communication', 'A2'),
  ('möjlig', 'possible', 'Allt är möjligt.', 'Everything is possible.', 'abstract', 'A2'),
  ('omöjlig', 'impossible', 'Det är helt omöjligt.', 'It is completely impossible.', 'abstract', 'B1'),
  ('kanske', 'maybe / perhaps', 'Kanske kommer det regna.', 'Maybe it will rain.', 'communication', 'A1'),

  -- Food & Kitchen (Expansion)
  ('tallrik', 'plate', 'Ställ tallriken på bordet.', 'Put the plate on the table.', 'kitchen', 'A1'),
  ('glas', 'glass', 'Vill du ha ett glas vatten?', 'Do you want a glass of water?', 'kitchen', 'A1'),
  ('kniv', 'knife', 'Kniven är vass.', 'The knife is sharp.', 'kitchen', 'A1'),
  ('gaffel', 'fork', 'Jag behöver en gaffel.', 'I need a fork.', 'kitchen', 'A1'),
  ('sked', 'spoon', 'Ät soppan med en sked.', 'Eat the soup with a spoon.', 'kitchen', 'A1'),
  ('gryta', 'pot / stew', 'Grytan står på spisen.', 'The pot is on the stove.', 'kitchen', 'A2'),
  ('stekpanna', 'frying pan', 'Stek fisken i en stekpanna.', 'Fry the fish in a frying pan.', 'kitchen', 'A2'),
  ('ugn', 'oven', 'Kakan är i ugnen.', 'The cake is in the oven.', 'kitchen', 'A1'),
  ('kylskåp', 'refrigerator', 'Mjölken står i kylskåpet.', 'The milk is in the fridge.', 'kitchen', 'A1'),
  ('recept', 'recipe', 'Jag har ett jättebra recept.', 'I have a great recipe.', 'kitchen', 'A2'),
  ('ingrediens', 'ingredient', 'Vilka ingredienser behöver vi?', 'Which ingredients do we need?', 'kitchen', 'B1'),
  ('smaka', 'to taste', 'Smaka på maten!', 'Taste the food!', 'kitchen', 'A1'),
  ('kryddor', 'spices', 'Vi behöver fler kryddor.', 'We need more spices.', 'kitchen', 'A2'),
  ('salt', 'salt', 'Kan jag få saltet?', 'Can I have the salt?', 'kitchen', 'A1'),
  ('peppar', 'pepper', 'Peppar ger bra smak.', 'Pepper gives good flavor.', 'kitchen', 'A1'),

  -- Nature & Animals (Expansion)
  ('hund', 'dog', 'Min hund heter Bamse.', 'My dog is named Bamse.', 'animals', 'A1'),
  ('katt', 'cat', 'Katten ligger i soffan.', 'The cat is lying on the sofa.', 'animals', 'A1'),
  ('fågel', 'bird', 'Fåglarna sjunger vackert.', 'The birds are singing beautifully.', 'animals', 'A1'),
  ('häst', 'horse', 'Hon älskar att rida hästar.', 'She loves to ride horses.', 'animals', 'A1'),
  ('ko', 'cow', 'Kon ger oss mjölk.', 'The cow gives us milk.', 'animals', 'A1'),
  ('älg', 'moose', 'Vi såg en älg i skogen.', 'We saw a moose in the forest.', 'animals', 'A2'),
  ('björn', 'bear', 'Björnen sover.', 'The bear is sleeping.', 'animals', 'A2'),
  ('varg', 'wolf', 'Vargen ylar mot månen.', 'The wolf is howling at the moon.', 'animals', 'B1'),
  ('fisk', 'fish', 'Det finns mycket fisk i sjön.', 'There are many fish in the lake.', 'animals', 'A1'),
  ('skog', 'forest', 'Jag gillar att plocka svamp i skogen.', 'I like picking mushrooms in the forest.', 'nature', 'A1'),
  ('trädgård', 'garden', 'Min trädgård är full av blommor.', 'My garden is full of flowers.', 'nature', 'A1'),
  ('hav', 'sea / ocean', 'Havet är djupt.', 'The sea is deep.', 'nature', 'A1'),
  ('strand', 'beach', 'Vi ska till stranden idag.', 'We are going to the beach today.', 'nature', 'A1'),
  ('sol', 'sun', 'Solen skiner idag.', 'The sun is shining today.', 'nature', 'A1'),
  ('måne', 'moon', 'Månen är hel ikväll.', 'The moon is full tonight.', 'nature', 'A1'),

  -- City & Architecture
  ('stad', 'city / town', 'Stockholm är en vacker stad.', 'Stockholm is a beautiful city.', 'city', 'A1'),
  ('gata', 'street', 'Vi bor på en lugn gata.', 'We live on a quiet street.', 'city', 'A1'),
  ('torg', 'square / plaza', 'Vi ses på torget.', 'See you at the square.', 'city', 'A1'),
  ('byggnad', 'building', 'Det här är en gammal byggnad.', 'This is an old building.', 'city', 'A2'),
  ('kyrka', 'church', 'Kyrkan har ett högt torn.', 'The church has a high tower.', 'city', 'A1'),
  ('museum', 'museum', 'Ska vi gå på museum?', 'Shall we go to a museum?', 'city', 'A1'),
  ('bibliotek', 'library', 'Jag lånar böcker på biblioteket.', 'I borrow books at the library.', 'city', 'A1'),
  ('bro', 'bridge', 'Vi kör över bron.', 'We are driving over the bridge.', 'city', 'A1'),
  ('hamn', 'harbor / port', 'Båtarna ligger i hamnen.', 'The boats are in the harbor.', 'city', 'A2'),
  ('centrum', 'center / downtown', 'Vi ska åka till centrum.', 'We are going downtown.', 'city', 'A1'),
  ('affär', 'shop / store', 'Affärerna stänger kl 20.', 'The shops close at 8 PM.', 'city', 'A1'),
  ('bio', 'cinema', 'Vi ska på bio ikväll.', 'We are going to the cinema tonight.', 'city', 'A1'),
  ('park', 'park', 'Hunden springer i parken.', 'The dog is running in the park.', 'city', 'A1'),
  ('restaurang', 'restaurant', 'Maten på restaurangen var god.', 'The food at the restaurant was good.', 'city', 'A1'),
  ('sjukhus', 'hospital', 'Sjukhuset ligger nära.', 'The hospital is nearby.', 'city', 'A1'),

  -- Career & Professional (Expansion)
  ('karriär', 'career', 'Hon vill göra karriär.', 'She wants to make a career.', 'career', 'B1'),
  ('presentation', 'presentation', 'Jag förbereder en presentation.', 'I am preparing a presentation.', 'career', 'B1'),
  ('samarbete', 'collaboration', 'Vårt samarbete fungerar bra.', 'Our collaboration is working well.', 'career', 'B1'),
  ('nätverk', 'network', 'Det är viktigt med ett bra nätverk.', 'A good network is important.', 'career', 'B2'),
  ('förhandling', 'negotiation', 'Förhandlingen var tuff.', 'The negotiation was tough.', 'career', 'B2'),
  ('strategi', 'strategy', 'Vi behöver en ny strategi.', 'We need a new strategy.', 'career', 'B2'),
  ('utmaning', 'challenge', 'Det här är en spännande utmaning.', 'This is an exciting challenge.', 'career', 'B1'),
  ('mål', 'goal', 'Vad är ditt mål?', 'What is your goal?', 'career', 'A2'),
  ('framgång', 'success', 'Hårt arbete leder till framgång.', 'Hard work leads to success.', 'career', 'B1'),
  ('misslyckande', 'failure', 'Vi lär oss av våra misslyckanden.', 'We learn from our failures.', 'career', 'B2'),
  ('feedback', 'feedback', 'Tack för din feedback.', 'Thank you for your feedback.', 'career', 'B1'),
  ('deadline', 'deadline', 'Vi har en deadline på fredag.', 'We have a deadline on Friday.', 'career', 'B1'),
  ('resurs', 'resource', 'Vi måste använda våra resurser väl.', 'We must use our resources well.', 'career', 'B2'),
  ('effektivit', 'efficiency', 'Vi vill öka vår effektivitet.', 'We want to increase our efficiency.', 'career', 'B2'),
  ('ledarskap', 'leadership', 'Ledarskap handlar om förtroende.', 'Leadership is about trust.', 'career', 'B2'),

  -- Feelings & Psychology (Expansion)
  ('själv förtroende', 'self-confidence', 'Han har dåligt självförtroende.', 'He has low self-confidence.', 'emotions', 'B2'),
  ('tacksam', 'grateful', 'Jag är så tacksam för din hjälp.', 'I am so grateful for your help.', 'emotions', 'A2'),
  ('stolt', 'proud', 'Jag är stolt över dig.', 'I am proud of you.', 'emotions', 'A1'),
  ('påkörd', 'hit (by a car) / overwhelmed', 'Jag känner mig helt påkörd.', 'I feel completely overwhelmed.', 'emotions', 'B2'),
  ('hoppfull', 'hopeful', 'Vi är hoppfulla inför framtiden.', 'We are hopeful for the future.', 'emotions', 'B1'),
  ('osäker', 'uncertain', 'Jag är osäker på vad jag ska göra.', 'I am uncertain about what to do.', 'emotions', 'A2'),
  ('trygg', 'secure / safe', 'Här känner jag mig trygg.', 'Here I feel safe.', 'emotions', 'A2'),
  ('stressad', 'stressed', 'Bli inte stressad.', 'Don''t get stressed.', 'emotions', 'A2'),
  ('avkopplad', 'relaxed', 'Det är skönt att vara avkopplad.', 'It is nice to be relaxed.', 'emotions', 'B1'),
  ('entusiastisk', 'enthusiastic', 'De var mycket entusiastiska.', 'They were very enthusiastic.', 'emotions', 'B2'),
  ('ensamhet', 'loneliness', 'Ensamhet kan vara svårt.', 'Loneliness can be difficult.', 'emotions', 'B1'),
  ('gemenskap', 'community / togetherness', 'Vi har en fin gemenskap här.', 'We have a nice community here.', 'emotions', 'B2'),
  ('kärlek', 'love', 'Kärlek övervinner allt.', 'Love conquers all.', 'emotions', 'A1'),
  ('hat', 'hate', 'Hat leder ingenstans.', 'Hate leads nowhere.', 'emotions', 'A2'),
  ('glädje', 'joy', 'Barnens glädje är smittsam.', 'The children''s joy is infectious.', 'emotions', 'A2')
ON CONFLICT (swedish) DO UPDATE SET
  english = EXCLUDED.english,
  example_sv = EXCLUDED.example_sv,
  example_en = EXCLUDED.example_en,
  category = EXCLUDED.category,
  level = EXCLUDED.level;
