-- ============================================
-- Learn Swedish: Vocab Expansion 200
-- 200+ Additional Words across existing categories
-- ============================================

INSERT INTO vocabulary (swedish, english, example_sv, example_en, category, level) VALUES
  -- Travel & Directions (15)
  ('flygplats', 'airport', 'Vi åker till flygplatsen nu.', 'We are going to the airport now.', 'travel', 'A1'),
  ('passagerare', 'passenger', 'Det var många passagerare på tåget.', 'There were many passengers on the train.', 'travel', 'A2'),
  ('försening', 'delay', 'Tåget har en försening på tio minuter.', 'The train has a delay of ten minutes.', 'travel', 'A2'),
  ('bagage', 'luggage', 'Var kan jag hämta mitt bagage?', 'Where can I pick up my luggage?', 'travel', 'A1'),
  ('avgång', 'departure', 'Avgången är klockan åtta.', 'The departure is at eight o''clock.', 'travel', 'A2'),
  ('ankomst', 'arrival', 'Vi väntar på din ankomst.', 'We are waiting for your arrival.', 'travel', 'A2'),
  ('turist', 'tourist', 'Många turister besöker Stockholm på sommaren.', 'Many tourists visit Stockholm in the summer.', 'travel', 'A1'),
  ('resa', 'journey / trip', 'Hur var din resa?', 'How was your journey?', 'travel', 'A1'),
  ('korsning', 'intersection', 'Sväng höger i nästa korsning.', 'Turn right at the next intersection.', 'directions', 'A2'),
  ('gathörn', 'street corner', 'Apoteket ligger i gathörnet.', 'The pharmacy is on the street corner.', 'directions', 'A2'),
  ('avstånd', 'distance', 'Avståndet till staden är kort.', 'The distance to the city is short.', 'travel', 'B1'),
  ('trafik', 'traffic', 'Det är mycket trafik idag.', 'There is a lot of traffic today.', 'travel', 'A2'),
  ('hyrbil', 'rental car', 'Vi bokade en hyrbil för resan.', 'We booked a rental car for the trip.', 'travel', 'A2'),
  ('vandrarhem', 'hostel', 'Ett vandrarhem är billigare än ett hotell.', 'A hostel is cheaper than a hotel.', 'travel', 'A2'),
  ('utflykt', 'excursion / trip', 'Idag gör vi en utflykt till naturen.', 'Today we are making an excursion to nature.', 'travel', 'B1'),

  -- Career & Work (15)
  ('yrke', 'profession / occupation', 'Vilket yrke har du?', 'What is your profession?', 'career', 'A1'),
  ('arbetsplats', 'workplace', 'Vi har en trevlig arbetsplats.', 'We have a nice workplace.', 'career', 'A2'),
  ('kollega', 'colleague', 'Jag ska äta lunch med en kollega.', 'I will have lunch with a colleague.', 'career', 'A1'),
  ('erfarenhet', 'experience', 'Har du mycket erfarenhet?', 'Do you have a lot of experience?', 'career', 'A2'),
  ('intervju', 'interview', 'Jag var nervös inför min intervju.', 'I was nervous before my interview.', 'career', 'A2'),
  ('ansökan', 'application', 'Skicka din ansökan innan fredag.', 'Send your application before Friday.', 'career', 'B1'),
  ('CV', 'CV / resume', 'Glöm inte att bifoga ditt CV.', 'Don''t forget to attach your resume.', 'career', 'A2'),
  ('avtal', 'contract / agreement', 'Vi skrev under ett nytt avtal i morse.', 'We signed a new contract this morning.', 'career', 'B2'),
  ('möte', 'meeting', 'Mötet börjar om en kvart.', 'The meeting starts in fifteen minutes.', 'career', 'A1'),
  ('rast', 'break', 'Nu är det dags för en kort rast.', 'Now it is time for a short break.', 'career', 'A1'),
  ('utmaning', 'challenge', 'Jag älskar en bra utmaning på jobbet.', 'I love a good challenge at work.', 'career', 'B1'),
  ('företag', 'company', 'Företaget växer snabbt.', 'The company is growing fast.', 'career', 'A2'),
  ('chef', 'boss / manager', 'Min chef är väldigt stöttande.', 'My boss is very supportive.', 'career', 'A1'),
  ('möjlighet', 'opportunity', 'Detta är en stor möjlighet för dig.', 'This is a great opportunity for you.', 'career', 'B1'),
  ('mål', 'goal / target', 'Vi nådde våra mål för året.', 'We reached our goals for the year.', 'career', 'A2'),

  -- Emotions & Feelings (15)
  ('kärlek', 'love', 'Kärlek är viktigt i livet.', 'Love is important in life.', 'emotions', 'A1'),
  ('glädje', 'joy', 'Barnens glädje smittar av sig.', 'The children''s joy is contagious.', 'emotions', 'A2'),
  ('sorg', 'sorrow / grief', 'Han kände en djup sorg.', 'He felt a deep sorrow.', 'emotions', 'B1'),
  ('spänning', 'excitement / tension', 'Spänningen var hög innan matchen.', 'The excitement was high before the game.', 'emotions', 'B1'),
  ('hopp', 'hope', 'Vi får aldrig förlora vårt hopp.', 'We must never lose our hope.', 'emotions', 'B1'),
  ('rädsla', 'fear', 'Hennes största rädsla är spindlar.', 'Her biggest fear is spiders.', 'emotions', 'A2'),
  ('ilska', 'anger', 'Han hade svårt att kontrollera sin ilska.', 'He had difficulty controlling his anger.', 'emotions', 'B2'),
  ('stolt', 'proud', 'Jag är mycket stolt över dig!', 'I am very proud of you!', 'emotions', 'A2'),
  ('ensam', 'lonely / alone', 'Ibland känner jag mig ensam.', 'Sometimes I feel lonely.', 'emotions', 'A2'),
  ('trygg', 'safe / secure', 'Här känner vi oss trygga.', 'Here we feel safe.', 'emotions', 'A2'),
  ('förvånad', 'surprised', 'Jag blev väldigt förvånad över nyheten.', 'I was very surprised by the news.', 'emotions', 'A2'),
  ('nyfiken', 'curious', 'Katten är väldigt nyfiken av sig.', 'The cat is very curious by nature.', 'emotions', 'A2'),
  ('tacksam', 'grateful', 'Jag är tacksam för all hjälp.', 'I am grateful for all the help.', 'emotions', 'A2'),
  ('besviken', 'disappointed', 'Hon var besviken över resultatet.', 'She was disappointed with the result.', 'emotions', 'B1'),
  ('bekymrad', 'worried / concerned', 'Läkaren såg lite bekymrad ut.', 'The doctor looked a bit worried.', 'emotions', 'B2'),

  -- Nature & Environment (15)
  ('hav', 'sea / ocean', 'Vi badade i havet varje dag.', 'We swam in the sea every day.', 'nature', 'A1'),
  ('strand', 'beach', 'Stranden var full av människor.', 'The beach was full of people.', 'nature', 'A1'),
  ('skog', 'forest', 'Jag gillar att promenera i skogen.', 'I like to walk in the forest.', 'nature', 'A1'),
  ('berg', 'mountain', 'Berget är mycket brant.', 'The mountain is very steep.', 'nature', 'A2'),
  ('dal', 'valley', 'I dalen ligger en liten by.', 'In the valley lies a small village.', 'nature', 'B1'),
  ('flod', 'river', 'Floden rinner genom staden.', 'The river flows through the city.', 'nature', 'A2'),
  ('sjö', 'lake', 'På sommaren brukar vi fiska i sjön.', 'In the summer we usually fish in the lake.', 'nature', 'A1'),
  ('ö', 'island', 'Sverige har många vackra öar.', 'Sweden has many beautiful islands.', 'nature', 'A2'),
  ('väder', 'weather', 'Idag är det fint väder.', 'Today the weather is nice.', 'nature', 'A1'),
  ('klimat', 'climate', 'Klimatet förändras snabbt i hela världen.', 'The climate is changing rapidly worldwide.', 'nature', 'B2'),
  ('miljö', 'environment', 'Vi måste ta hand om vår miljö.', 'We must take care of our environment.', 'nature', 'B1'),
  ('natur', 'nature', 'Svensk natur är fantastisk.', 'Swedish nature is fantastic.', 'nature', 'A1'),
  ('landskap', 'landscape', 'Landskapet i norr är väldigt vilt.', 'The landscape in the north is very wild.', 'nature', 'A2'),
  ('stjärna', 'star', 'Stjärnorna lyste klart inatt.', 'The stars shone brightly tonight.', 'nature', 'A1'),
  ('måne', 'moon', 'Månen är helt full.', 'The moon is completely full.', 'nature', 'A1'),

  -- Technology & Media (15)
  ('skräm', 'screen', 'Datorskärmen är väldigt stor.', 'The computer screen is very large.', 'technology', 'A1'),
  ('tangentbord', 'keyboard', 'Jag behöver ett nytt tangentbord.', 'I need a new keyboard.', 'technology', 'A2'),
  ('mus', 'mouse (computer)', 'Musen fungerar inte bra.', 'The mouse is not working well.', 'technology', 'A1'),
  ('lösenord', 'password', 'Ditt lösenord är felaktigt.', 'Your password is incorrect.', 'technology', 'A2'),
  ('användare', 'user', 'Vi har hundra nya användare.', 'We have a hundred new users.', 'technology', 'A2'),
  ('meddelande', 'message', 'Jag fick ditt meddelande nyss.', 'I just received your message.', 'technology', 'A1'),
  ('nätverk', 'network', 'Nätverket är långsamt idag.', 'The network is slow today.', 'technology', 'B1'),
  ('program', 'program / app', 'Vilket program använder du för detta?', 'Which program do you use for this?', 'technology', 'A2'),
  ('uppdatering', 'update', 'En ny uppdatering finns tillgänglig.', 'A new update is available.', 'technology', 'B1'),
  ('ladda ner', 'to download', 'Du kan ladda ner boken härifrån.', 'You can download the book from here.', 'technology', 'A2'),
  ('information', 'information', 'Här finns mer information om kursen.', 'Here is more information about the course.', 'media', 'A1'),
  ('nyhet', 'news', 'Har du hört den senaste nyheten?', 'Have you heard the latest news?', 'media', 'A2'),
  ('reklam', 'advertising / commercial', 'TV-programmet avbröts av reklam.', 'The TV program was interrupted by commercials.', 'media', 'A2'),
  ('tidning', 'newspaper / magazine', 'Han läser tidningen vid frukosten.', 'He reads the newspaper at breakfast.', 'media', 'A1'),
  ('artikel', 'article', 'Artikeln var väldigt intressant.', 'The article was very interesting.', 'media', 'A2'),

  -- Home & Household (15)
  ('tak', 'roof / ceiling', 'Taket läcker in vatten.', 'The roof is leaking water.', 'home', 'A2'),
  ('golv', 'floor', 'Golvet är gjort av trä.', 'The floor is made of wood.', 'home', 'A1'),
  ('vägg', 'wall', 'Vi målade väggen vit.', 'We painted the wall white.', 'home', 'A1'),
  ('fönster', 'window', 'Vänligen öppna ett fönster.', 'Please open a window.', 'home', 'A1'),
  ('dörr', 'door', 'Stäng dörren efter dig.', 'Close the door after you.', 'home', 'A1'),
  ('nyckel', 'key', 'Jag har tappat min nyckel.', 'I have lost my key.', 'home', 'A1'),
  ('trappa', 'stair / staircase', 'Trappan upp är ganska brant.', 'The stairs up are quite steep.', 'home', 'A2'),
  ('hylla', 'shelf', 'Boken står på översta hyllan.', 'The book is on the top shelf.', 'home', 'A2'),
  ('säng', 'bed', 'Min säng är väldigt mjuk.', 'My bed is very soft.', 'home', 'A1'),
  ('kudde', 'pillow', 'Jag behöver en till kudde.', 'I need an additional pillow.', 'home', 'A1'),
  ('täcke', 'blanket / duvet', 'Det är kallt, ge mig ett täcke.', 'It is cold, give me a duvet.', 'home', 'A1'),
  ('matta', 'rug / carpet', 'Katten sover på mattan.', 'The cat is sleeping on the rug.', 'home', 'A1'),
  ('lampa', 'lamp', 'Tänd lampan i vardagsrummet.', 'Turn on the lamp in the living room.', 'home', 'A1'),
  ('spegel', 'mirror', 'Hon tittade sig i spegeln.', 'She looked at herself in the mirror.', 'home', 'A1'),
  ('handduk', 'towel', 'Har vi rena handdukar?', 'Do we have clean towels?', 'home', 'A1'),

  -- Adjectives & Descriptors (20)
  ('stor', 'big / large', 'Elefanten är mycket stor.', 'The elephant is very big.', 'adjectives', 'A1'),
  ('liten', 'small / little', 'Hon bor i ett litet hus.', 'She lives in a small house.', 'adjectives', 'A1'),
  ('lång', 'long / tall', 'Han är väldigt lång.', 'He is very tall.', 'adjectives', 'A1'),
  ('kort', 'short', 'Mötet var ganska kort.', 'The meeting was quite short.', 'adjectives', 'A1'),
  ('tjock', 'thick / fat', 'Boken är väldigt tjock.', 'The book is very thick.', 'adjectives', 'A2'),
  ('tunn', 'thin', 'Jackan är för tunn för vintern.', 'The jacket is too thin for winter.', 'adjectives', 'A2'),
  ('bra', 'good', 'Det var en jättebra film.', 'It was a very good movie.', 'adjectives', 'A1'),
  ('dålig', 'bad', 'Kvaliteten är tyvärr ganska dålig.', 'The quality is unfortunately quite bad.', 'adjectives', 'A1'),
  ('snabb', 'fast', 'Tåget är ett snabbt sätt att resa.', 'The train is a fast way to travel.', 'adjectives', 'A1'),
  ('långsam', 'slow', 'Snigeln är ett långsamt djur.', 'The snail is a slow animal.', 'adjectives', 'A1'),
  ('svår', 'difficult / hard', 'Detta är ett svårt problem att lösa.', 'This is a difficult problem to solve.', 'adjectives', 'A1'),
  ('lätt', 'easy / light', 'Uppgiften var väldigt lätt.', 'The task was very easy.', 'adjectives', 'A1'),
  ('stark', 'strong', 'Han är lika stark som en oxe.', 'He is as strong as an ox.', 'adjectives', 'A2'),
  ('svag', 'weak', 'Kaffet är lite för svagt.', 'The coffee is a bit too weak.', 'adjectives', 'A2'),
  ('ung', 'young', 'Som barn var han mycket energisk.', 'As young he was very energetic.', 'adjectives', 'A1'),
  ('gammal', 'old', 'Det är en väldigt gammal kyrka.', 'It is a very old church.', 'adjectives', 'A1'),
  ('hög', 'high / tall', 'Trädet är extremt högt.', 'The tree is extremely high.', 'adjectives', 'A1'),
  ('låg', 'low', 'Rösten var mörk och låg.', 'The voice was dark and low.', 'adjectives', 'A1'),
  ('varm', 'warm / hot', 'Vattnet känns jättevarmt.', 'The water feels very hot.', 'adjectives', 'A1'),
  ('kall', 'cold', 'Det är en kall vinter.', 'It is a cold winter.', 'adjectives', 'A1'),

  -- Health & Body (15)
  ('kropp', 'body', 'Kroppen behöver vila ibland.', 'The body needs rest sometimes.', 'body', 'A1'),
  ('hälsa', 'health', 'Hälsan är det viktigaste vi har.', 'Health is the most important thing we have.', 'health', 'A2'),
  ('sjuk', 'sick / ill', 'Jag måste stanna hemma, jag är sjuk.', 'I must stay home, I am sick.', 'health', 'A1'),
  ('frisk', 'healthy', 'Nu känner jag mig helt frisk igen.', 'Now I feel completely healthy again.', 'health', 'A2'),
  ('ont', 'pain / ache', 'Jag har ont i magen.', 'I have pain in my stomach.', 'health', 'A1'),
  ('sjukhus', 'hospital', 'Olyckan hände nära sjukhuset.', 'The accident happened near the hospital.', 'health', 'A1'),
  ('läkare', 'doctor', 'Ring en läkare, snälla.', 'Call a doctor, please.', 'health', 'A1'),
  ('tandläkare', 'dentist', 'Jag går till tandläkaren en gång om året.', 'I go to the dentist once a year.', 'health', 'A2'),
  ('apotek', 'pharmacy', 'Var är närmaste apotek?', 'Where is the nearest pharmacy?', 'health', 'A1'),
  ('medicin', 'medicine', 'Denna medicin hjälper mot huvudvärk.', 'This medicine helps against headaches.', 'health', 'A2'),
  ('blod', 'blood', 'Jag är lite rädd för blod.', 'I am a bit afraid of blood.', 'body', 'B1'),
  ('hjärta', 'heart', 'Hjärtat slår snabbt.', 'The heart is beating fast.', 'body', 'A2'),
  ('mage', 'stomach', 'Min mage är helt tom.', 'My stomach is completely empty.', 'body', 'A2'),
  ('rygg', 'back', 'Han fick ont i ryggen av att lyfta tungt.', 'He got back pain from lifting heavy.', 'body', 'A2'),
  ('hals', 'throat / neck', 'Jag känner mig lite tjock i halsen.', 'I feel a bit congested in my throat.', 'body', 'B1'),

  -- Leisure & Hobbies (15)
  ('fritid', 'leisure time / free time', 'Jag läser böcker på min fritid.', 'I read books in my free time.', 'leisure', 'A1'),
  ('hobby', 'hobby', 'Vad har du för hobby?', 'What hobby do you have?', 'leisure', 'A1'),
  ('sport', 'sports', 'Min favoritsport är ishockey.', 'My favorite sport is ice hockey.', 'leisure', 'A1'),
  ('match', 'game / match', 'Ska vi titta på matchen ikväll?', 'Shall we watch the game tonight?', 'leisure', 'A1'),
  ('lag', 'team', 'Sveriges lag spelade väldigt bra.', 'Sweden''s team played very well.', 'leisure', 'A2'),
  ('musik', 'music', 'Vilken sorts musik föredrar du?', 'What kind of music do you prefer?', 'leisure', 'A1'),
  ('instrument', 'instrument', 'Spelar du något instrument?', 'Do you play any instrument?', 'leisure', 'A2'),
  ('konsert', 'concert', 'Biljetterna till konserten var dyra.', 'The tickets for the concert were expensive.', 'leisure', 'A2'),
  ('film', 'movie', 'Har du sett den nya filmen?', 'Have you seen the new movie?', 'leisure', 'A1'),
  ('teater', 'theater', 'Vi ska gå på teater på fredag.', 'We are going to the theater on Friday.', 'leisure', 'A2'),
  ('konst', 'art', 'Modern konst är svår att förstå ibland.', 'Modern art is difficult to understand sometimes.', 'leisure', 'B1'),
  ('museum', 'museum', 'Vasamuseet är fantastiskt.', 'The Vasa museum is amazing.', 'leisure', 'A1'),
  ('bok', 'book', 'Just nu läser jag en spännande bok.', 'Right now I am reading an exciting book.', 'leisure', 'A1'),
  ('spel', 'game', 'Ska vi spela ett brädspel?', 'Shall we play a board game?', 'leisure', 'A2'),
  ('promenad', 'walk', 'Vi tog en mysig promenad i skogen.', 'We took a cozy walk in the forest.', 'leisure', 'A1'),

  -- Clothing & Fashion (15)
  ('kläder', 'clothes', 'Mina kläder är tyvärr blöta.', 'My clothes are unfortunately wet.', 'fashion', 'A1'),
  ('skor', 'shoes', 'Ta av dig skorna innanför dörren.', 'Take off your shoes inside the door.', 'fashion', 'A1'),
  ('strumpor', 'socks', 'Jag har tappat ena strumpan.', 'I have lost one sock.', 'fashion', 'A1'),
  ('byxor', 'pants / trousers', 'Ena fickan på byxorna är trasig.', 'One pocket on the pants is broken.', 'fashion', 'A2'),
  ('tröja', 'sweater', 'Den här tjocka tröjan är väldigt varm.', 'This thick sweater is very warm.', 'fashion', 'A1'),
  ('skjorta', 'shirt (button-up)', 'Han hade på sig en fin vit skjorta.', 'He was wearing a nice white shirt.', 'fashion', 'A2'),
  ('klänning', 'dress', 'Hon köpte en ny röd klänning inför festen.', 'She bought a new red dress for the party.', 'fashion', 'A2'),
  ('kjol', 'skirt', 'Kjolen fladdrade i vinden.', 'The skirt fluttered in the wind.', 'fashion', 'A2'),
  ('jacka', 'jacket', 'Du behöver en tjock jacka när det är kallt.', 'You need a thick jacket when it is cold.', 'fashion', 'A1'),
  ('kappa', 'coat', 'Hennes vinterkappa var väldigt elegant.', 'Her winter coat was very elegant.', 'fashion', 'B1'),
  ('mössa', 'beanie / winter hat', 'Glöm inte mössan, det fryser på.', 'Don''t forget the beanie, it''s freezing.', 'fashion', 'A2'),
  ('vantar', 'mittens / gloves', 'Mina fingrar fryser, var är mina vantar?', 'My fingers are freezing, where are my mittens?', 'fashion', 'A2'),
  ('halsduk', 'scarf', 'Hon virade halsduken flera varv runt halsen.', 'She wrapped the scarf several times around her neck.', 'fashion', 'B1'),
  ('mode', 'fashion', 'Svenskt mode är ofta minimalistiskt.', 'Swedish fashion is often minimalistic.', 'fashion', 'B1'),
  ('storlek', 'size', 'Den här tröjan är inte i min storlek.', 'This sweater is not in my size.', 'fashion', 'A2'),

  -- Education & Learning (15)
  ('skola', 'school', 'Min dotter trivs väldigt bra i skolan.', 'My daughter enjoys school very much.', 'education', 'A1'),
  ('förskola', 'preschool', 'Förskolan stänger klockan sjutton.', 'The preschool closes at seventeen.', 'education', 'A2'),
  ('elev', 'student / pupil', 'Läraren hjälpte en elev med räkningen.', 'The teacher helped a student with math.', 'education', 'A2'),
  ('lärare', 'teacher', 'Vår lärare pratar flytande franska.', 'Our teacher speaks fluent French.', 'education', 'A1'),
  ('student', 'university student', 'Studenterna hade mycket att läsa.', 'The university students had a lot to read.', 'education', 'A2'),
  ('lektion', 'lesson / class', 'Mattelektionen var ovanligt rolig idag.', 'The math lesson was unusually fun today.', 'education', 'A1'),
  ('rast', 'recess / break', 'Nu ringer klockan för rast.', 'Now the bell rings for recess.', 'education', 'A1'),
  ('prov', 'exam / test', 'Blev du godkänd på provet?', 'Did you pass the exam?', 'education', 'A2'),
  ('betyg', 'grade', 'Hans betyg räckte för att komma in.', 'His grades were enough to get in.', 'education', 'B1'),
  ('läxa', 'homework', 'Glöm inte din läxa till imorgon.', 'Don''t forget your homework for tomorrow.', 'education', 'A1'),
  ('ämne', 'subject', 'Vilket är ditt favoritämne?', 'Which is your favorite subject?', 'education', 'A2'),
  ('kunskap', 'knowledge', 'Kunskap är makt brukar man säga.', 'Knowledge is power they say.', 'education', 'B1'),
  ('utbildning', 'education / training', 'Jag behöver mer utbildning inom detta.', 'I need more training in this.', 'education', 'B1'),
  ('universitet', 'university', 'Lunds universitet är känt över hela världen.', 'Lund University is known all over the world.', 'education', 'A2'),
  ('forskning', 'research', 'Forskningen visar på stora förbättringar.', 'The research shows huge improvements.', 'education', 'B2'),

  -- Food & Kitchen (15)
  ('mat', 'food', 'Svensk mat kan vara lite speciell.', 'Swedish food can be a bit special.', 'food', 'A1'),
  ('dryck', 'beverage / drink', 'Vad önskar du för dryck?', 'What beverage do you wish?', 'food', 'A2'),
  ('frukost', 'breakfast', 'Frukosten ingår i priset på hotellet.', 'Breakfast is included in the price at the hotel.', 'food', 'A1'),
  ('lunch', 'lunch', 'Vi äter lunch vid tolvslaget.', 'We eat lunch at twelve o''clock.', 'food', 'A1'),
  ('middag', 'dinner', 'Middagen serveras klockan arton.', 'Dinner is served at eighteen.', 'food', 'A1'),
  ('tallrik', 'plate', 'Ställ tallriken på bänken, tack.', 'Put the plate on the counter, please.', 'food', 'A1'),
  ('glas', 'glass', 'Kan jag få ett till glas juice?', 'Can I have one more glass of juice?', 'food', 'A1'),
  ('kniv', 'knife', 'Var försiktig, kniven är vass.', 'Be careful, the knife is sharp.', 'food', 'A2'),
  ('gaffel', 'fork', 'Vi behöver en till gaffel här.', 'We need another fork here.', 'food', 'A1'),
  ('sked', 'spoon', 'Rör om kaffet med en sked.', 'Stir the coffee with a spoon.', 'food', 'A2'),
  ('ugn', 'oven', 'Kakan ska vara i ugnen i 20 minuter.', 'The cake should be in the oven for 20 minutes.', 'food', 'A2'),
  ('spis', 'stove', 'Spisen är fortfarande varm.', 'The stove is still hot.', 'food', 'A2'),
  ('kylskåp', 'refrigerator', 'Ställ in mjölken i kylskåpet.', 'Put the milk in the fridge.', 'food', 'A1'),
  ('frys', 'freezer', 'Vi har mycket bär i vår frys.', 'We have many berries in our freezer.', 'food', 'A2'),
  ('recept', 'recipe', 'Receptet är hemligt i min familj.', 'The recipe is a secret in my family.', 'food', 'A2'),

  -- Abstract Concepts (10)
  ('frihet', 'freedom', 'Människors frihet måste alltid skyddas.', 'People''s freedom must always be protected.', 'abstract', 'B1'),
  ('rättvisa', 'justice', 'Vi kämpar för rättvisa i samhället.', 'We fight for justice in society.', 'abstract', 'B1'),
  ('sanning', 'truth', 'Det är dags att höra sanningen.', 'It is time to hear the truth.', 'abstract', 'B1'),
  ('lögn', 'lie', 'Det där är en ren lögn.', 'That is a pure lie.', 'abstract', 'B1'),
  ('förändring', 'change', 'Förändring kan ibland kännas svårt.', 'Change can sometimes feel difficult.', 'abstract', 'B1'),
  ('framtid', 'future', 'Framtiden ser ljus ut för oss.', 'The future looks bright for us.', 'abstract', 'A2'),
  ('dåtid', 'past', 'Hon tänker ofta på det förflutna och sin dåtid.', 'She often thinks of the past.', 'abstract', 'B2'),
  ('kultur', 'culture', 'Svensk kultur är mer än bara köttbullar.', 'Swedish culture is more than just meatballs.', 'abstract', 'B1'),
  ('samhälle', 'society', 'Alla är en viktig del av vårt samhälle.', 'Everyone is an important part of our society.', 'abstract', 'B1'),
  ('demokrati', 'democracy', 'Demokrati är inte alltid självklart.', 'Democracy is not always to be taken for granted.', 'abstract', 'B2')
ON CONFLICT DO NOTHING;
