-- ============================================
-- Learn Swedish: Category Balancing (~280 words)
-- Focusing on Animals, Greetings, Daily Life, Media, etc.
-- ============================================

INSERT INTO vocabulary (swedish, english, example_sv, example_en, category, level) VALUES
  -- Animals (+30)
  ('elefant', 'elephant', 'Elefanten på zoo var gigantisk.', 'The elephant at the zoo was gigantic.', 'animals', 'A1'),
  ('lejon', 'lion', 'Lejonet ryter högt.', 'The lion roars loudly.', 'animals', 'A2'),
  ('tiger', 'tiger', 'Tigern har ränder.', 'The tiger has stripes.', 'animals', 'A2'),
  ('krokodil', 'crocodile', 'Krokodilen låg och solade.', 'The crocodile was lying and sunbathing.', 'animals', 'B1'),
  ('djur', 'animal', 'Vilket är ditt favoritdjur?', 'Which is your favorite animal?', 'animals', 'A1'),
  ('kanin', 'rabbit', 'Kaninen äter en morot.', 'The rabbit is eating a carrot.', 'animals', 'A1'),
  ('mus', 'mouse', 'Katten jagar en mus.', 'The cat is chasing a mouse.', 'animals', 'A1'),
  ('råtta', 'rat', 'Det sprang en råtta över gatan.', 'A rat ran across the street.', 'animals', 'A2'),
  ('ko', 'cow', 'Korna betar på ängen.', 'The cows are grazing in the meadow.', 'animals', 'A1'),
  ('gris', 'pig', 'Grisarna rullar sig i leran.', 'The pigs roll in the mud.', 'animals', 'A1'),
  ('får', 'sheep', 'Fåren har mycket ull.', 'The sheep have a lot of wool.', 'animals', 'A2'),
  ('get', 'goat', 'Geten kan klättra bra.', 'The goat can climb well.', 'animals', 'A2'),
  ('höna', 'hen / chicken', 'Hönan lade ett ägg.', 'The hen laid an egg.', 'animals', 'A1'),
  ('tupp', 'rooster', 'Tuppen gal tidigt på morgonen.', 'The rooster crows early in the morning.', 'animals', 'A2'),
  ('anka', 'duck', 'Ankorna simmar i dammen.', 'The ducks are swimming in the pond.', 'animals', 'A1'),
  ('fågel', 'bird', 'En liten fågel sjöng i trädet.', 'A small bird sang in the tree.', 'animals', 'A1'),
  ('örn', 'eagle', 'Örnen flyger högt uppe i skyn.', 'The eagle flies high up in the sky.', 'animals', 'B1'),
  ('uggla', 'owl', 'Ugglan är vaken på natten.', 'The owl is awake at night.', 'animals', 'A2'),
  ('orm', 'snake', 'Jag är väldigt rädd för ormar.', 'I am very afraid of snakes.', 'animals', 'A2'),
  ('groda', 'frog', 'Grodan hoppade ner i vattnet.', 'The frog jumped down into the water.', 'animals', 'A2'),
  ('fisk', 'fish', 'Akvariet är fyllt med färgstarka fiskar.', 'The aquarium is filled with colorful fishes.', 'animals', 'A1'),
  ('haj', 'shark', 'Hajen har vassa tänder.', 'The shark has sharp teeth.', 'animals', 'A2'),
  ('val', 'whale', 'Blåvalen är det största djuret i världen.', 'The blue whale is the largest animal in the world.', 'animals', 'B1'),
  ('delfin', 'dolphin', 'Delfinerna lekte vid båten.', 'The dolphins played by the boat.', 'animals', 'B1'),
  ('spindel', 'spider', 'Det sitter en spindel i hörnet.', 'There is a spider sitting in the corner.', 'animals', 'A2'),
  ('myra', 'ant', 'En myra kan bära flera gånger sin egen vikt.', 'An ant can carry several times its own weight.', 'animals', 'A2'),
  ('fluga', 'fly', 'Det är en irriterande fluga i rummet.', 'There is an annoying fly in the room.', 'animals', 'A1'),
  ('mygg', 'mosquito', 'Myggorna är hemska på sommaren.', 'The mosquitoes are awful in the summer.', 'animals', 'A2'),
  ('insekt', 'insect', 'Barnen letade efter coola insekter.', 'The children were looking for cool insects.', 'animals', 'A2'),
  ('älg', 'moose', 'Älgen kallas ofta skogens konung.', 'The moose is often called the king of the forest.', 'animals', 'A2'),

  -- Greetings & Expressions (+25)
  ('god kväll', 'good evening', 'God kväll. Har ni ett bord för två?', 'Good evening. Do you have a table for two?', 'greetings', 'A1'),
  ('tjena', 'hey (casual)', 'Tjena! Läget?', 'Hey! What''s up?', 'greetings', 'A2'),
  ('hallå', 'hello (on phone / calling out)', 'Hallå, är någon där?', 'Hello, is anyone there?', 'greetings', 'A1'),
  ('hejdå', 'goodbye', 'Vi måste gå nu. Hejdå!', 'We have to leave now. Goodbye!', 'greetings', 'A1'),
  ('vi ses', 'see you', 'Trevlig helg, vi ses på måndag!', 'Have a nice weekend, see you on Monday!', 'greetings', 'A1'),
  ('hur mår du', 'how are you', 'Hej Anna! Hur mår du idag?', 'Hello Anna! How are you today?', 'greetings', 'A1'),
  ('bra tack', 'good thanks', 'Jag mår bara bra tack, och du?', 'I feel just fine thanks, and you?', 'greetings', 'A1'),
  ('välkommen', 'welcome', 'Välkommen till vår vackra stad!', 'Welcome to our beautiful city!', 'greetings', 'A1'),
  ('trevligt att träffas', 'nice to meet you', 'Mycket trevligt att träffas!', 'Very nice to meet you!', 'greetings', 'A1'),
  ('varsågod', 'here you go / you''re welcome', 'Varsågod, här är din kaffe.', 'Here you go, here is your coffee.', 'greetings', 'A1'),
  ('tack så mycket', 'thank you very much', 'Tack så jättemycket för hjälpen.', 'Thank you very much for the help.', 'greetings', 'A1'),
  ('ingen orsak', 'no problem / don''t mention it', 'Det var så lite. Ingen orsak!', 'It was nothing. No problem!', 'greetings', 'A2'),
  ('förlåt', 'sorry / forgive me', 'Förlåt, jag menade det inte.', 'Sorry, I didn''t mean it.', 'greetings', 'A1'),
  ('ursäkta', 'excuse me', 'Ursäkta, får jag fråga dig en sak?', 'Excuse me, may I ask you something?', 'greetings', 'A1'),
  ('snälla', 'please (only for pleading)', 'Snälla, kan du hjälpa mig?', 'Please, can you help me?', 'greetings', 'A2'),
  ('tyvärr', 'unfortunately', 'Tyvärr har vi stängt.', 'Unfortunately we are closed.', 'greetings', 'A2'),
  ('lycka till', 'good luck', 'Lycka till på provet imorgon!', 'Good luck on the test tomorrow!', 'greetings', 'A1'),
  ('grattis', 'congratulations', 'Grattis på födelsedagen!', 'Happy birthday! (Congratulations on the birthday)', 'greetings', 'A1'),
  ('skål', 'cheers', 'Skål för framtiden!', 'Cheers to the future!', 'greetings', 'A2'),
  ('krya på dig', 'get well soon', 'Jag hörde att du var sjuk. Krya på dig!', 'I heard you were sick. Get well soon!', 'greetings', 'A2'),
  ('ha det bra', 'take care / have a good one', 'Vi pratas vid! Ha det så bra!', 'We will talk! Take care!', 'greetings', 'A2'),
  ('jag pratar inte svenska', 'I don''t speak swedish', 'Förlåt, men jag pratar tyvärr inte svenska.', 'Sorry, but I unfortunately don''t speak Swedish.', 'greetings', 'A1'),
  ('pratar du engelska', 'do you speak english', 'Ursäkta, men pratar du engelska?', 'Excuse me, but do you speak English?', 'greetings', 'A1'),
  ('jag förstår inte', 'I don''t understand', 'Kan du prata långsammare? Jag förstår inte.', 'Can you speak slower? I don''t understand.', 'greetings', 'A1'),
  ('klart', 'clear / done / of course', 'Klart vi ska hjälpa till!', 'Of course we will help!', 'greetings', 'A2'),

  -- Daily Life / Routine (+25)
  ('vakna', 'to wake up', 'Klockan ringer och jag måste vakna.', 'The alarm goes off and I have to wake up.', 'daily life', 'A1'),
  ('gå upp', 'to get up', 'Jag går upp klockan sju.', 'I get up at seven o''clock.', 'daily life', 'A1'),
  ('tvätta sig', 'to wash oneself', 'Låt mig bara tvätta mig i ansiktet först.', 'Let me just wash my face first.', 'daily life', 'A2'),
  ('borsta', 'to brush', 'Glöm inte att borsta tänderna.', 'Do not forget to brush your teeth.', 'daily life', 'A1'),
  ('duscha', 'to shower', 'Jag tar en snabb dusch varje morgon.', 'I take a quick shower every morning.', 'daily life', 'A1'),
  ('sminka sig', 'to put on makeup', 'Hon sminkar sig framför spegeln.', 'She puts on makeup in front of the mirror.', 'daily life', 'A2'),
  ('klä på sig', 'to get dressed', 'Sedan klär jag på mig mina kläder.', 'Then I get dressed in my clothes.', 'daily life', 'A2'),
  ('äta frukost', 'eat breakfast', 'Vid åtta brukar vi äta frukost.', 'At eight we usually eat breakfast.', 'daily life', 'A1'),
  ('gå till jobbet', 'go to work', 'Sedan måste jag gå till jobbet.', 'Then I have to go to work.', 'daily life', 'A1'),
  ('börja', 'to begin / start', 'Mötet börjar prick nio.', 'The meeting starts exactly at nine.', 'daily life', 'A1'),
  ('arbeta', 'to work', 'Jag arbetar fram till kl 17.', 'I work until 5 PM.', 'daily life', 'A1'),
  ('sluta', 'to stop / finish', 'När slutar du för dagen?', 'When do you finish for the day?', 'daily life', 'A1'),
  ('äta lunch', 'eat lunch', 'Vi ska ut och äta lunch nu.', 'We are going out to eat lunch now.', 'daily life', 'A1'),
  ('äta middag', 'eat dinner', 'Vem lagar middag ikväll?', 'Who is cooking dinner tonight?', 'daily life', 'A1'),
  ('diska', 'to do the dishes', 'Jag hatar verkligen att diska.', 'I really hate doing the dishes.', 'daily life', 'A2'),
  ('tvätta', 'to do laundry / wash', 'Maskinen håller på att tvätta kläderna.', 'The machine is currently washing the clothes.', 'daily life', 'A2'),
  ('handla', 'to shop (grocery)', 'Jag måste handla mat på vägen hem.', 'I have to buy groceries on my way home.', 'daily life', 'A1'),
  ('städa', 'to clean', 'Vi måste städa huset innan gästerna kommer.', 'We have to clean the house before the guests arrive.', 'daily life', 'A1'),
  ('dammsuga', 'to vacuum', 'Golvet är smutsigt, jag borde dammsuga.', 'The floor is dirty, I should vacuum.', 'daily life', 'A2'),
  ('laga mat', 'to cook', 'Jag älskar att laga mat åt min familj.', 'I love cooking for my family.', 'daily life', 'A1'),
  ('vila', 'to rest', 'Du ser trött ut, försök att vila lite.', 'You look tired, try to rest a bit.', 'daily life', 'A2'),
  ('leka', 'to play (children/animals)', 'Barnen gillar att leka ute.', 'The children like to play outside.', 'daily life', 'A1'),
  ('lägga sig', 'to go to bed', 'Jag är trött. Det är dags att lägga sig.', 'I am tired. It is time to go to bed.', 'daily life', 'A1'),
  ('sova', 'to sleep', 'Bäbisen ligger och sover sött.', 'The baby is sleeping sweetly.', 'daily life', 'A1'),
  ('drömma', 'to dream', 'Vad brukar du drömma om på natten?', 'What do you usually dream about at night?', 'daily life', 'B1'),

  -- Media & Entertainment (+25)
  ('film', 'movie / film', 'Filmen hade biopremiär igår.', 'The movie premiered in cinemas yesterday.', 'media', 'A1'),
  ('biograf', 'cinema', 'Det finns en stor biograf i centrum.', 'There is a large cinema downtown.', 'media', 'A1'),
  ('radio', 'radio', 'Vi brukade lyssna på radio i bilen.', 'We used to listen to the radio in the car.', 'media', 'A1'),
  ('teve', 'television', 'Stäng av storslagen så länge.', 'Turn off the TV for now.', 'media', 'A1'),
  ('program', 'program / show', 'Detta är mitt favoritprogram på TV.', 'This is my favorite TV show.', 'media', 'A1'),
  ('kanal', 'channel', 'Kan du byta kanal?', 'Can you change the channel?', 'media', 'A2'),
  ('skådespelare', 'actor / actress', 'Han är en av de kändaste skådespelarna.', 'He is one of the most famous actors.', 'media', 'A2'),
  ('tidning', 'newspaper', 'Många läser tidningen på bussen.', 'Many read the newspaper on the bus.', 'media', 'A1'),
  ('magasin', 'magazine', 'Ett nytt livsstilsmagasin har lanserats.', 'A new lifestyle magazine has launched.', 'media', 'B1'),
  ('nyheter', 'news', 'Klockan åtta visas alltid de senaste nyheterna.', 'At eight o''clock the latest news is always shown.', 'media', 'A1'),
  ('journal', 'journal / newscast', 'Se kvällens journal för mer detaljer.', 'Watch the evening newscast for more details.', 'media', 'B2'),
  ('dator', 'computer', 'Många spelar spel på datorn idag.', 'Many play games on the computer today.', 'media', 'A1'),
  ('internet', 'internet', 'Tänk om internet skulle sluta fungera.', 'Imagine if the internet stopped working.', 'media', 'A1'),
  ('webbsida', 'web page / website', 'Vår webbsida har kraschat.', 'Our website has crashed.', 'media', 'A2'),
  ('applikation', 'application / app', 'Vilken smidig liten app!', 'What a smooth little app!', 'media', 'A2'),
  ('podcast', 'podcast', 'Jag gillar att lyssna på roliga poddar.', 'I like listening to funny podcasts.', 'media', 'A2'),
  ('musik', 'music', 'Särskilt mycket folk kom för musiken.', 'Especially many people came for the music.', 'media', 'A1'),
  ('konsert', 'concert', 'Harley spelade en minnesvärd konsert igår.', 'Harley played a memorable concert yesterday.', 'media', 'B1'),
  ('låt', 'song / track', 'Detta är en fantastiskt bra låt!', 'This is a fantastic song!', 'media', 'A1'),
  ('artist', 'artist / singer', 'Denna artist är på uppgång i Europa.', 'This artist is rising in Europe.', 'media', 'B1'),
  ('spel', 'game', 'Det är ett spännande nytt spel.', 'It is an exciting new game.', 'media', 'A1'),
  ('teater', 'theater', 'Hon sågs le uppe på teaterns scen.', 'She was seen smiling up on the theater''s stage.', 'media', 'A2'),
  ('biljett', 'ticket', 'Spara biljetten, du behöver den i insläppet.', 'Keep the ticket, you need it at the entrance.', 'media', 'A1'),
  ('recension', 'review', 'Tyvärr fick filmen ganska dåliga recensioner.', 'Unfortunately the movie got pretty bad reviews.', 'media', 'B2'),
  ('underhållning', 'entertainment', 'Parken bjuder på god underhållning för barn.', 'The park offers good entertainment for children.', 'media', 'B1'),

  -- Pronouns & Particles (+25)
  ('vem', 'who', 'Vem är det som knackar på dörren?', 'Who is knocking on the door?', 'pronouns', 'A1'),
  ('vad', 'what', 'Vad vill du äta till middag?', 'What do you want to eat for dinner?', 'pronouns', 'A1'),
  ('var', 'where (location)', 'Ursäkta, vet du var toaletten är?', 'Excuse me, do you know where the bathroom is?', 'pronouns', 'A1'),
  ('vart', 'where (destination)', 'Vart är ni på väg just nu?', 'Where are you heading right now?', 'pronouns', 'A2'),
  ('när', 'when', 'När slutar du skolan idag?', 'When do you finish school today?', 'pronouns', 'A1'),
  ('varför', 'why', 'Varför är himlen blå?', 'Why is the sky blue?', 'pronouns', 'A1'),
  ('hur', 'how', 'Hur vet man att vinet är bra?', 'How do you know the wine is good?', 'pronouns', 'A1'),
  ('vilken', 'which / what (en-words)', 'Vilken väg är snabbast, tror du?', 'Which way is the fastest, you reckon?', 'pronouns', 'A2'),
  ('vilket', 'which / what (ett-words)', 'Vilket hus bor du i?', 'Which house do you live in?', 'pronouns', 'A2'),
  ('vem som helst', 'anyone / anybody', 'Regeln gäller för vem som helst.', 'The rule applies to anyone.', 'pronouns', 'B1'),
  ('vad som helst', 'anything', 'Du får önska dig precis vad som helst.', 'You can wish for absolutely anything.', 'pronouns', 'B1'),
  ('min', 'my / mine', 'Det här är min kaffekopp', 'This is my coffee cup.', 'pronouns', 'A1'),
  ('din', 'your / yours', 'Är detta din jacka?', 'Is this your jacket?', 'pronouns', 'A1'),
  ('hans', 'his', 'Detta är hans hund.', 'This is his dog.', 'pronouns', 'A1'),
  ('hennes', 'her / hers', 'Tyvärr tappade hon hennes plånbok där.', 'Unfortunately she dropped her wallet there.', 'pronouns', 'A1'),
  ('deras', 'their / theirs', 'Gatan var ockuperad av deras bilar.', 'The street was occupied by their cars.', 'pronouns', 'A2'),
  ('vår', 'our', 'Vi älskar vår stad.', 'We love our city.', 'pronouns', 'A1'),
  ('mig', 'me', 'Kom och ge mig en kram!', 'Come and give me a hug!', 'pronouns', 'A1'),
  ('dig', 'you (object)', 'Det är roligt att se dig igen.', 'It is fun to see you again.', 'pronouns', 'A1'),
  ('det', 'it / that (ett)', 'Är det alltid så här kallt i Sverige?', 'Is it always this cold in Sweden?', 'pronouns', 'A1'),
  ('den', 'it / that (en)', 'Ge katten mjölk. Den är hungrig.', 'Give the cat milk. It is hungry.', 'pronouns', 'A1'),
  ('de', 'they', 'De åker buss varje morgon.', 'They take the bus every morning.', 'pronouns', 'A1'),
  ('dem', 'them', 'Det är svårt att förstå dem ibland.', 'It is hard to understand them sometimes.', 'pronouns', 'A2'),
  ('här', 'here', 'Kom hit, stå här bredvid mig.', 'Come here, stand here next to me.', 'pronouns', 'A1'),
  ('där', 'there', 'Ställ ifrån dig lådan där borta.', 'Put down the box over there.', 'pronouns', 'A1'),

  -- Directions & Location (+25)
  ('karta', 'map', 'Vi saknade vår fysiska karta.', 'We missed our physical map.', 'directions', 'B1'),
  ('adress', 'address', 'Vilken var din adress igen?', 'What was your address again?', 'directions', 'A1'),
  ('gata', 'street', 'Titta efter rätt gata på skylten.', 'Look for the right street on the sign.', 'directions', 'A1'),
  ('väg', 'road / way', 'Nu är vi nog på helt fel väg.', 'Now we are probably on the completely wrong road.', 'directions', 'A2'),
  ('höger', 'right', 'Kör rakt fram till det högra fältet.', 'Drive straight ahead into the right lane.', 'directions', 'A1'),
  ('vänster', 'left', 'Jag håller pennan i min vänstra hand.', 'I hold the pen in my left hand.', 'directions', 'A1'),
  ('framåt', 'forward / ahead', 'Man måste hålla fokus framåt.', 'You have to keep focus ahead.', 'directions', 'B1'),
  ('bakåt', 'backward', 'Bilen rullade tyvärr lite bakåt.', 'The car unfortunately rolled a bit backward.', 'directions', 'A2'),
  ('upp', 'up', 'Titta upp på den vackra fågeln!', 'Look up at the beautiful bird!', 'directions', 'A1'),
  ('ner', 'down', 'Snälla kom direkt ner till köket.', 'Please come right down to the kitchen.', 'directions', 'A1'),
  ('över', 'over / across', 'Ska vi hoppa över staketet?', 'Shall we jump over the fence?', 'directions', 'A2'),
  ('under', 'under / below', 'Hunden gömmer sig under sängen.', 'The dog is hiding under the bed.', 'directions', 'A1'),
  ('framför', 'in front of', 'Parkera inte bilen framför vår dörr.', 'Do not park the car in front of our door.', 'directions', 'A2'),
  ('bakom', 'behind', 'Vi gömde nyckeln bakom den lilla krukan.', 'We hid the key behind the little pot.', 'directions', 'A2'),
  ('bredvid', 'next to', 'Skolan ligger bara precis bredvid.', 'The school is located just right next to.', 'directions', 'A1'),
  ('mellan', 'between', 'Ställ radion mellan skålet och vasen.', 'Place the radio between the bowl and the vase.', 'directions', 'A2'),
  ('nära', 'near / close', 'Sjukhuset ligger mycket nära.', 'The hospital is located very near.', 'directions', 'A1'),
  ('långt', 'far', 'Tyvärr var det extremt långt bort.', 'Unfortunately it was extremely far away.', 'directions', 'A1'),
  ('mot', 'towards', 'Kör mot den stora kyrkan i centrum.', 'Drive towards the large church downtown.', 'directions', 'B1'),
  ('in', 'in / inside', 'Vi måste ta oss in direkt.', 'We have to get inside immediately.', 'directions', 'A1'),
  ('ut', 'out / outside', 'Det är så varmt att vi drar ut.', 'It feels so warm that we march outside.', 'directions', 'A1'),
  ('inomhus', 'indoors', 'Katten föredrar att vara inomhus idag.', 'The cat prefers being indoors today.', 'directions', 'A2'),
  ('utomhus', 'outdoors', 'Sport utomhus är ofta mycket trivsamt.', 'Sports outdoors is often very pleasant.', 'directions', 'A2'),
  ('härifrån', 'from here', 'Stationen ligger bara en minut härifrån.', 'The station is only a minute from here.', 'directions', 'A2'),
  -- Numbers & Quantities (+25)
  ('noll', 'zero', 'Temperaturen var under noll igår.', 'The temperature was below zero yesterday.', 'numbers', 'A1'),
  ('sex', 'six', 'Vi behöver sex ägg till kakan.', 'We need six eggs for the cake.', 'numbers', 'A1'),
  ('sju', 'seven', 'Det finns sju dagar i en vecka.', 'There are seven days in a week.', 'numbers', 'A1'),
  ('åtta', 'eight', 'Klockan åtta börjar nyheterna.', 'At eight o''clock the news starts.', 'numbers', 'A1'),
  ('nio', 'nine', 'Kan vi ses klockan nio istället?', 'Can we meet at nine instead?', 'numbers', 'A1'),
  ('tio', 'ten', 'Hon köpte tio röda rosor.', 'She bought ten red roses.', 'numbers', 'A1'),
  ('elva', 'eleven', 'Laget består av elva spelare.', 'The team consists of eleven players.', 'numbers', 'A2'),
  ('tolv', 'twelve', 'Det är tolv månader på ett år.', 'There are twelve months in a year.', 'numbers', 'A2'),
  ('hundra', 'hundred', 'Skjortan kostade över fem hundra kronor.', 'The shirt cost over five hundred kronor.', 'numbers', 'A1'),
  ('tusen', 'thousand', 'Flera tusen besökare förväntades komma.', 'Several thousand visitors were expected to come.', 'numbers', 'A1'),
  ('miljon', 'million', 'Stockholm har över en miljon invånare.', 'Stockholm has over a million inhabitants.', 'numbers', 'A2'),
  ('hälften', 'half', 'Hälften av befolkningen röstade inte.', 'Half of the population didn''t vote.', 'numbers', 'B1'),
  ('en fjärdedel', 'a quarter', 'Bara en fjärdedel av pizzan finns kvar.', 'Only a quarter of the pizza is left.', 'numbers', 'B2'),
  ('en tredjedel', 'a third', 'Han drack upp en tredjedel av vattnet.', 'He drank a third of the water.', 'numbers', 'B2'),
  ('fler', 'more (countable)', 'Vi skulle behöva fler stolar här.', 'We would need more chairs here.', 'numbers', 'A2'),
  ('flest', 'most (countable)', 'Det laget gjorde flest perfekta mål.', 'That team scored the most perfect goals.', 'numbers', 'A2'),
  ('mycket', 'much / a lot', 'Den maskinen kostade tyvärr ganska mycket.', 'That machine unfortunately cost quite a lot.', 'numbers', 'A1'),
  ('lite', 'a little / a few', 'Snälla, kan jag bara få lite mjölk?', 'Please, can I just have a little milk?', 'numbers', 'A1'),
  ('många', 'many', 'Det hänger många tavlor på väggen.', 'There are many paintings hanging on the wall.', 'numbers', 'A1'),
  ('få', 'few', 'Under kvällen valde väldigt få att delta.', 'During the evening very few chose to participate.', 'numbers', 'A2'),
  ('allt', 'everything / all', 'Är verkligen allt material packat?', 'Is really all material packed?', 'numbers', 'A1'),
  ('alla', 'everyone / all', 'Nästan alla mina vänner bor numera utomlands.', 'Almost all my friends nowadays live abroad.', 'numbers', 'A2'),
  ('ingen', 'no one / nobody', 'Varför var det absolut ingen på festen?', 'Why was there absolutely nobody at the party?', 'numbers', 'A2'),
  ('inget', 'nothing', 'Man hade inget val under svåra tiden.', 'One had nothing of a choice during the hard time.', 'numbers', 'B1'),
  ('något', 'something / anything', 'Ska vi kika efter något gott att äta?', 'Shall we look for something tasty to eat?', 'numbers', 'A2'),

  -- Body & Health (+20)
  ('ansikte', 'face', 'Ditt ansikte lyser utav vacker glädje.', 'Your face shines with beautiful joy.', 'body', 'A1'),
  ('näsa', 'nose', 'Luften känns kall rakt på min näsa.', 'The air feels cold straight on my nose.', 'body', 'A1'),
  ('hår', 'hair', 'Vinden blåser försiktigt genom hennes hår.', 'The wind blows gently through her hair.', 'body', 'A1'),
  ('läppar', 'lips', 'Hon hade röda varma läppar inatt.', 'She had red warm lips tonight.', 'body', 'B1'),
  ('arm', 'arm', 'Din vänstra arm ser ganska skadad ut.', 'Your left arm looks quite damaged.', 'body', 'A1'),
  ('ben', 'leg', 'Sitt inte med benen i kors så mycket.', 'Don''t sit with your legs crossed so much.', 'body', 'A1'),
  ('knä', 'knee', 'Ett knä gör lite ont efter all löpning.', 'One knee hurts a bit after all the running.', 'body', 'A2'),
  ('axlar', 'shoulders', 'Tyngden drog snabbt ner hennes axlar.', 'The weight quickly pulled her shoulders down.', 'body', 'A2'),
  ('blod', 'blood', 'Såret blödde en väldigt liten droppe blod.', 'The wound bled a very small drop of blood.', 'health', 'A2'),
  ('hud', 'skin', 'Det var viktigt att försiktigt tvätta sin hud.', 'It was important to carefully wash one''s skin.', 'body', 'B2'),
  ('feber', 'fever', 'Barnet hade hög feber över natten.', 'The child had a high fever over night.', 'health', 'A2'),
  ('hosta', 'cough', 'Du borde köpa något medicin för din hosta.', 'You should buy some medicine for your cough.', 'health', 'A2'),
  ('snuva', 'runny nose / cold', 'Hösten förer tyvärr med sig mycket snuva.', 'The autumn unfortunately brings a lot of snuva.', 'health', 'B1'),
  ('smärta', 'pain', 'Han upplevde en intensiv och snabb smärta.', 'He experienced an intense and fast pain.', 'health', 'B1'),
  ('sjukdom', 'disease / illness', 'Ingen fruktansvärd sjukdom ska få stoppa mig.', 'No terrible illness shall be allowed to stop me.', 'health', 'B2'),
  ('patient', 'patient', 'Sjuksköterskan pratade trevligt med patienten.', 'The nurse talked nicely with the patient.', 'health', 'B1'),
  ('plåster', 'band-aid / plaster', 'Behöver du bara ett enkelt litet plåster?', 'Do you only need a simple little band-aid?', 'health', 'A1'),
  ('apotek', 'pharmacy', 'Letar efter nattöppet apotek vid torget.', 'Searching for night-open pharmacy at the square.', 'health', 'A2'),
  ('vikt', 'weight', 'Det sägs att regelbunden träning håller god vikt.', 'It is said that regular workout keeps good weight.', 'health', 'A2'),
  ('sömn', 'sleep', 'Bra och djup sömn underlättar stressen imorgon.', 'Good and deep sleep eases the stress tomorrow.', 'health', 'A2'),

  -- Communication & Conversation (+20)
  ('språk', 'language', 'Vilket språk talar de främst i hemlandet?', 'Which language do they primarily speak in the homeland?', 'communication', 'A1'),
  ('ord', 'word', 'Det var oerhört svårt att hitta rätt ord nu.', 'It was terribly difficult to find the right word now.', 'communication', 'A1'),
  ('mening', 'sentence / meaning', 'Kan du skriva ner hela samma mening en gång till?', 'Can you write down the whole same sentence one more time?', 'communication', 'A2'),
  ('fråga', 'question', 'Har vi egentligen tid för just en sista fråga nu?', 'Do we really have time for exactly one last question now?', 'communication', 'A1'),
  ('svar', 'answer', 'Vi förväntade oss inte ett så fantastiskt jättesvar.', 'We did not expect such a fantastic huge answer.', 'communication', 'A1'),
  ('samtal', 'conversation', 'Pojkarna hade ett intressant och långt kvällssamtal.', 'The boys had an interesting and long evening conversation.', 'communication', 'A2'),
  ('att prata', 'to speak / talk', 'Jag älskar verkligen att prata oavbrutet hela kvällen.', 'I truly love to talk non-stop the whole evening.', 'communication', 'A1'),
  ('att säga', 'to say', 'Vad brukade lilla Olle försiktigt säga oftast?', 'What did little Olle carefully use to say most often?', 'communication', 'A1'),
  ('att ropa', 'to shout / call', 'Mamma brukade genast ropa ner oss var morgon.', 'Mom used to instantly call us down every morning.', 'communication', 'B1'),
  ('att viska', 'to whisper', 'Du måste lugnt viska hemligheten noga för mig.', 'You must calmly whisper the secret carefully to me.', 'communication', 'B2'),
  ('röst', 'voice', 'Sångerskan hade enormt stark mjuk röst på scenen.', 'The singer had enormously strong soft voice on stage.', 'communication', 'A2'),
  ('ton', 'tone', 'Håll en vänligare varmare ton inför mötet imorgon.', 'Keep a friendlier warmer tone before the meeting tomorrow.', 'communication', 'B1'),
  ('att förklara', 'to explain', 'Jag önskar du enkelt kunde förklara saken tydligt.', 'I wish you could simply explain the matter clearly.', 'communication', 'B1'),
  ('att beskriva', 'to describe', 'Det gällde helt att beskriva rummet ganska snabbt.', 'It applied completely to describe the room quite quickly.', 'communication', 'B2'),
  ('ljud', 'sound', 'Det plötsliga mörka kalla ljudet skrämde oss vilt.', 'The sudden dark cold sound scared us wildly.', 'communication', 'A2'),
  ('tystnad', 'silence', 'Bara fullständig helt tystnad regerade salongen länge.', 'Only complete totally silence ruled the salon long.', 'communication', 'B1'),
  ('att lyssna', 'to listen', 'Vi glömde snabbt bort att lyssna uppmärksamt under lektionen.', 'We quickly forgot to listen attentively during the lesson.', 'communication', 'A1'),
  ('att höra', 'to hear', 'Kan du överhuvudtaget någonsin höra bilar inifrån huset?', 'Can you overall ever hear cars from inside the house?', 'communication', 'A1'),
  ('meddelande', 'message', 'Chefen lämnade hastigt ett tydligt extremt argt meddelande.', 'The boss hastily left a clear extremely angry message.', 'communication', 'A2'),
  -- City & Places (+20)
  ('stad', 'city', 'Den gamla staden har mycket vacker arkitektur.', 'The old city has very beautiful architecture.', 'city', 'A1'),
  ('by', 'village', 'Han växte upp i en väldigt liten by.', 'He grew up in a very small village.', 'city', 'A1'),
  ('gata', 'street', 'Titta alltid åt båda hållen innan du korsar gatan.', 'Always look both ways before crossing the street.', 'city', 'A1'),
  ('väg', 'road', 'Det var mörkt och isigt på vägen hem.', 'It was dark and icy on the road home.', 'city', 'A2'),
  ('torg', 'square', 'Folk samlades snabbt på det soliga torget.', 'People quickly gathered on the sunny square.', 'city', 'A1'),
  ('park', 'park', 'Att äta glass i parken är mysigt.', 'Eating ice cream in the park is cozy.', 'city', 'A1'),
  ('butik', 'store / shop', 'Klädbutiken stängde alltid klockan sju på kvällen.', 'The clothing store always closed at seven in the evening.', 'city', 'A1'),
  ('affär', 'shop', 'Gå snabbt till affären och köp mjölk.', 'Go quickly to the shop and buy milk.', 'city', 'A1'),
  ('restaurang', 'restaurant', 'Vilken trevlig och väldigt populär restaurang det var!', 'What a nice and very popular restaurant it was!', 'city', 'A1'),
  ('café', 'cafe', 'Låt oss sätta oss på det nya lilla caféet.', 'Let us sit down at the new little cafe.', 'city', 'A1'),
  ('skola', 'school', 'Skolan slutar ganska tidigt på fredagarna numera.', 'The school finishes quite early on the Fridays nowadays.', 'city', 'A1'),
  ('sjukhus', 'hospital', 'Sjukhuset låg plötsligt väldigt långt borta tyvärr.', 'The hospital was suddenly located very far away unfortunately.', 'city', 'A1'),
  ('apotek', 'pharmacy', 'Apoteket ligger i centrum på samma gata.', 'The pharmacy is located downtown on the same street.', 'city', 'A2'),
  ('bank', 'bank', 'Banken är tyvärr stängd på själva helgen.', 'The bank is unfortunately closed on the actual weekend.', 'city', 'A2'),
  ('post', 'post office / mail', 'Jag måste snabbt springa ner till posten.', 'I must quickly run down to the post office.', 'city', 'A2'),
  ('polis', 'police', 'Någon ringde polisen efter den stora smällen.', 'Someone called the police after the big bang.', 'city', 'A1'),
  ('kyrka', 'church', 'Söndagsskolan hölls inuti den stora gamla kyrkan.', 'The Sunday school was held inside the big old church.', 'city', 'A1'),
  ('bibliotek', 'library', 'Det måste vara lugnt och helt tyst på biblioteket.', 'It must be calm and completely quiet in the library.', 'city', 'A1'),
  ('museum', 'museum', 'Sveriges största museum ligger mitt inne i skogen.', 'Sweden''s largest museum is located right inside the forest.', 'city', 'A1'),
  ('byggnad', 'building', 'Det är en fruktansvärt ful modern byggnad.', 'It is a terribly ugly modern building.', 'city', 'B1'),

  -- Time & Calendar (+20)
  ('tid', 'time', 'Har vi egentligen tillräckligt mycket tid kvar?', 'Do we really have enough time left?', 'time', 'A1'),
  ('år', 'year', 'Ett år går alldeles för märkligt fort ibland.', 'A year passes all too strangely fast sometimes.', 'time', 'A1'),
  ('månad', 'month', 'Augusti är oftast en riktigt varm svensk månad.', 'August is usually a really warm Swedish month.', 'time', 'A1'),
  ('vecka', 'week', 'Vilken dag i nästa vecka kan du bäst?', 'Which day next week can you best?', 'time', 'A1'),
  ('dag', 'day', 'Idag är det verkligen en mycket vacker dag.', 'Today it is really a very beautiful day.', 'time', 'A1'),
  ('timme', 'hour', 'Filmen var exakt en timme och tjugo minuter.', 'The movie was exactly one hour and twenty minutes.', 'time', 'A1'),
  ('minut', 'minute', 'Vänta här i bara exakt en kort minut.', 'Wait here for just exactly one short minute.', 'time', 'A1'),
  ('sekund', 'second', 'Han försvann bakom dörren på bara en sekund.', 'He disappeared behind the door in just one second.', 'time', 'A2'),
  ('morgon', 'morning', 'Jag älskar kaffe tidigt direkt på morgonen.', 'I love coffee early directly in the morning.', 'time', 'A1'),
  ('förmiddag', 'before noon', 'Mötet hölls sent på själva tisdagens förmiddag.', 'The meeting was held late on the actual Tuesday''s before-noon.', 'time', 'A2'),
  ('eftermiddag', 'afternoon', 'Solen är starkast på den sena varma eftermiddagen.', 'The sun is strongest in the late warm afternoon.', 'time', 'A2'),
  ('kväll', 'evening', 'Vi brukar oftast titta på TV nästan varje kväll.', 'We usually watch TV almost every evening.', 'time', 'A1'),
  ('natt', 'night', 'Stjärnorna lyste alldeles extremt starkt mitt i natten.', 'The stars shone absolutely extremely bright in the middle of the night.', 'time', 'A1'),
  ('idag', 'today', 'Hur är det fantastiska vädret ute egentligen idag?', 'How is the fantastic weather outside actually today?', 'time', 'A1'),
  ('igår', 'yesterday', 'Mitt husdjur mådde lite dåligt under hela dagen igår.', 'My pet felt a little bad during the whole day yesterday.', 'time', 'A1'),
  ('imorgon', 'tomorrow', 'Ska vi åka iväg någonstans redan imorgon bitti?', 'Shall we go away somewhere already tomorrow morning?', 'time', 'A1'),
  ('tidigt', 'early', 'Varför måste du vakna upp så otroligt tidigt jämt?', 'Why do you have to wake up so incredibly early always?', 'time', 'A1'),
  ('sent', 'late', 'Tåget blev tyvärr ganska oväntat väldigt sent igen.', 'The train unfortunately unexpectedly became very late again.', 'time', 'A1'),
  ('nu', 'now', 'Det är absolut hög tid att gå ut nu direkt.', 'It is absolutely high time to go out right now.', 'time', 'A1'),
  ('då', 'then', 'Vi får helt enkelt ta diskussionen vidare då istället.', 'We will simply have to take the discussion further then instead.', 'time', 'A2'),

  -- Travel & Transportation (+15)
  ('bil', 'car', 'Den röda snabba bilen körde förbi extremt fort.', 'The red fast car drove by extremely quickly.', 'travel', 'A1'),
  ('buss', 'bus', 'Sitter du ofta långt bak inne i bussen?', 'Do you often sit far back inside the bus?', 'travel', 'A1'),
  ('tåg', 'train', 'Många älskar att åka på långa varma tåg.', 'Many love to travel on long warm trains.', 'travel', 'A1'),
  ('cykel', 'bicycle', 'Ta cykeln om du verkligen vill få motion.', 'Take the bicycle if you really want to get exercise.', 'travel', 'A1'),
  ('flygplan', 'airplane', 'Min bror är oerhört flygrädd för höga flygplan.', 'My brother is terribly flight-scared of high airplanes.', 'travel', 'A2'),
  ('båt', 'boat', 'På sommaren brukar vi hyra en liten vit båt.', 'In the summer we usually rent a little white boat.', 'travel', 'A2'),
  ('station', 'station', 'Gå gärna direkt ner mot den centrala stationen.', 'Feel free to go straight down towards the central station.', 'travel', 'A1'),
  ('biljett', 'ticket', 'Det var nästan omöjligt att hitta min biljett sedan.', 'It was almost impossible to find my ticket afterwards.', 'travel', 'A1'),
  ('resa', 'journey', 'Vilken oförutsägbar och utmanande lång resa det blev!', 'What an unpredictable and challenging long journey it became!', 'travel', 'B1'),
  ('pass', 'passport', 'Suck, varför glömmer jag alltid mitt dyra pass?', 'Sigh, why do I always forget my expensive passport?', 'travel', 'A1'),
  ('väska', 'bag', 'Farmors väska visade sig vara väldigt fasansfullt tung.', 'Grandma''s bag turned out to be terribly horribly heavy.', 'travel', 'A1'),
  ('hotell', 'hotel', 'Bokade ni verkligen rum på samma lyxiga hotell?', 'Did you really book room at the same luxurious hotel?', 'travel', 'A1'),
  ('turist', 'tourist', 'Staden fullkomligt översvämmades av glada vilsna turister idag.', 'The city completely flooded of happy lost tourists today.', 'travel', 'A2'),
  ('karta', 'map', 'Utan en stor detaljerad karta är vi helt vilse.', 'Without a large detailed map we are completely lost.', 'travel', 'B2'),
  ('flygplats', 'airport', 'Det fanns inget kaffe alls nere på den tomma flygplatsen.', 'There was no coffee at all down at the empty airport.', 'travel', 'A2'),

  -- Technology & Internet (+15)
  ('dator', 'computer', 'Pappas nya stora svarta dator kraschade nästan genast igen.', 'Dad''s new big black computer crashed almost immediately again.', 'technology', 'A1'),
  ('telefon', 'telephone', 'Svara genast i den ringande lila telefonen, tack!', 'Answer immediately in the ringing purple phone, please!', 'technology', 'A1'),
  ('skärm', 'screen', 'Texten var svår att läsa på den lilla ljusa skärmen.', 'The text was hard to read on the small bright screen.', 'technology', 'A2'),
  ('tangentbord', 'keyboard', 'Jag spillde vatten rätt över mitt snygga dyra tangentbord nyss.', 'I spilled water right across my good-looking expensive keyboard just now.', 'technology', 'A2'),
  ('mus', 'mouse (computer)', 'Den sladdlösa datormusen slutade bara plötsligt att alls fungera.', 'The cordless computer-mouse just suddenly stopped working at all.', 'technology', 'A2'),
  ('knapp', 'button', 'Vad händer om jag råkar trycka på den stora röda knappen?', 'What happens if I accidentally press the big red button?', 'technology', 'A2'),
  ('internet', 'internet', 'Vårt internet är förfärligt osäkert och långsamt ibland.', 'Our internet is terribly insecure and slow sometimes.', 'technology', 'A1'),
  ('webbsida', 'website', 'Jag hittade tyvärr absolut ingen alls relevant webbsida om saken.', 'I unfortunately found absolutely no relevant website about the matter at all.', 'technology', 'B1'),
  ('länk', 'link', 'Du behöver bara desperat klicka på denna blinkande blå länk.', 'You just desperately need to click on this blinking blue link.', 'technology', 'A2'),
  ('lösenord', 'password', 'Välj ett riktigt starkt och långt komplicerat löneord till kontot.', 'Choose a really strong and long complicated password to the account.', 'technology', 'A2'),
  ('användare', 'user', 'Systemet kunde enkelt hantera oändligt många vanliga samtidiga användare.', 'The system could easily handle infinite many common simultaneous users.', 'technology', 'B2'),
  ('meddelande', 'message', 'Ett mycket kort mystiskt meddelande dök helt oväntat upp igår.', 'A very short mysterious message showed up completely unexpectedly yesterday.', 'technology', 'B1'),
  ('app', 'app', 'Ladda gärna ned min superbra nya lilla app imorgon bitti.', 'Please download my super-good new little app tomorrow morning.', 'technology', 'A1'),
  ('fil', 'file', 'Bifogade du den enorma digitala bildfilen till det allra sista mailet?', 'Did you attach the huge digital image-file to the very last mail?', 'technology', 'B1'),
  ('nätverk', 'network', 'Inget osäkert trådlöst nätverk var tydligen tillgängligt att omedelbart ansluta till.', 'No insecure wireless network was apparently available to immediately connect to.', 'technology', 'B2'),

  -- Food & Kitchen (+10)
  ('mat', 'food', 'Svensk traditionell julmat är verkligen fruktansvärt bedårande underbart gott.', 'Swedish traditional Christmas-food is really terribly adorably wonderfully tasty.', 'food', 'A1'),
  ('frukost', 'breakfast', 'Gjorde du iordning en stor ordentlig stadig god frukost till oss?', 'Did you prepare a big proper steady good breakfast for us?', 'food', 'A1'),
  ('lunch', 'lunch', 'Pasta verkar vara den absolut mest supervanliga bästa svenska lunchen.', 'Pasta seems to be the absolutely most super-common best Swedish lunch.', 'food', 'A1'),
  ('middag', 'dinner', 'Vem ansvarar för att laga hela den komplicerade svåra sena middagen ikväll?', 'Who is responsible for cooking the whole complicated difficult late dinner tonight?', 'food', 'A1'),
  ('bröd', 'bread', 'Nybakat mörkt surdegsbröd smakar faktiskt ofta bara allra allra helt fantastiskt bäst.', 'Fresh-baked dark sourdough-bread actually often simply tastes most completely fantastic best.', 'food', 'A1'),
  ('smör', 'butter', 'Glöm bara inte att bre tjockt mjukt fint äkta svenskt smör ovanpå.', 'Just do not forget to spread thick soft nice real Swedish butter on top.', 'food', 'A1'),
  ('ost', 'cheese', 'Sverige producerar oerhört intressant stark fantastisk smakrik god lagrad magisk hård ost.', 'Sweden produces extremely interesting strong fantastic flavorful good aged magical hard cheese.', 'food', 'A2'),
  ('ägg', 'egg', 'Ett perfekt hårdkokt stort ägg passar väl bra till varje tidig lördagsfrukost.', 'A perfect hard-boiled large egg fits well for every early Saturday-breakfast.', 'food', 'A1'),
  ('mjölk', 'milk', 'Komjölk är tyvärr tyvärr numera kanske relativt betydligt alltmer extremt impopulärt idag.', 'Cow-milk is unfortunately unfortunately nowadays perhaps relatively significantly increasingly extremely unpopular today.', 'food', 'A1'),
  ('vatten', 'water', 'Kallt rinnande svenskt kranvatten har i särklass överlägset absolut hela världens allra renaste bästa finaste kvalitet.', 'Cold running Swedish tap-water has by far overwhelmingly absolutely the whole world''s purest best finest quality.', 'food', 'A1')
ON CONFLICT DO NOTHING;
